# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mvdrr/mvdrr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr || ORIG_REF_NAME==mvdrr} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_versal_cips_0_0/mvdrr_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_versal_cips_0_0 || ORIG_REF_NAME==mvdrr_versal_cips_0_0} -quiet] -quiet

# Block Designs: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/bd_342f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_342f || ORIG_REF_NAME==bd_342f} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/bd_342f_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_342f_pspmc_0_0 || ORIG_REF_NAME==bd_342f_pspmc_0_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_axi_noc_0_0 || ORIG_REF_NAME==mvdrr_axi_noc_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_clk_wizard_0_0 || ORIG_REF_NAME==mvdrr_clk_wizard_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_proc_sys_reset_0_0/mvdrr_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_proc_sys_reset_0_0 || ORIG_REF_NAME==mvdrr_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_axi_dma_0_0/mvdrr_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_axi_dma_0_0 || ORIG_REF_NAME==mvdrr_axi_dma_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_smartconnect_0_0/mvdrr_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_smartconnect_0_0 || ORIG_REF_NAME==mvdrr_smartconnect_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_smartconnect_1_0/mvdrr_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_smartconnect_1_0 || ORIG_REF_NAME==mvdrr_smartconnect_1_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/mvdrr_rdbs_kernel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_rdbs_kernel_0_0 || ORIG_REF_NAME==mvdrr_rdbs_kernel_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_covariance_estimation_0_0/mvdrr_covariance_estimation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_covariance_estimation_0_0 || ORIG_REF_NAME==mvdrr_covariance_estimation_0_0} -quiet] -quiet

# IP: bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/mvdrr_mvdr_weights_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdrr_mvdr_weights_0_0 || ORIG_REF_NAME==mvdrr_mvdr_weights_0_0} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/bd_342f_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_342f_pspmc_0_0 || ORIG_REF_NAME==bd_342f_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_342f_pspmc_0_0 || ORIG_REF_NAME==bd_342f_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/bd_342f_ooc.xdc

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/mvdrr_ooc.xdc
