# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.runs/synth_1/mvdrr_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.flow 0
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvc1902-vsva2197-2MP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.cache/wt [current_project]
set_property parent.project_path C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vck190:part0:3.4 [current_project]
set_property ip_repo_paths {
  c:/Users/Deepraj/Desktop/WORK/istrac/ip/covariance_kernel
  c:/Users/Deepraj/Desktop/WORK/istrac/ip/mvdr_kernel
  c:/Users/Deepraj/Desktop/WORK/istrac/ip/rdbs_kernel
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/hdl/mvdrr_wrapper.v
add_files C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/mvdrr.bd
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/bd_342f_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_versal_cips_0_0/bd_0/bd_342f_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48f7_S00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48f7_S06_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48f7_S01_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48f7_S02_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_48f7_S03_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_48f7_S04_AXI_rpu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_48f7_S05_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_48f7_S07_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_9/xdc/bd_48f7_S08_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/hdl/par/bd_48f7_MC0_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_proc_sys_reset_0_0/mvdrr_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_proc_sys_reset_0_0/mvdrr_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_dma_0_0/mvdrr_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_dma_0_0/mvdrr_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_dma_0_0/mvdrr_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_1/bd_0f28_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_2/bd_0f28_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_3/bd_0f28_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_4/bd_0f28_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_5/bd_0f28_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_6/bd_0f28_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_7/bd_0f28_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_8/bd_0f28_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_9/bd_0f28_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_10/bd_0f28_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_11/bd_0f28_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_12/bd_0f28_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_13/bd_0f28_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_14/bd_0f28_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_15/bd_0f28_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_16/bd_0f28_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_20/bd_0f28_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_21/bd_0f28_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_22/bd_0f28_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_23/bd_0f28_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_24/bd_0f28_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_25/bd_0f28_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_26/bd_0f28_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_27/bd_0f28_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_28/bd_0f28_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_29/bd_0f28_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_30/bd_0f28_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_31/bd_0f28_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_33/bd_0f28_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_34/bd_0f28_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_35/bd_0f28_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_36/bd_0f28_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_37/bd_0f28_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_38/bd_0f28_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_40/bd_0f28_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_41/bd_0f28_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_42/bd_0f28_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_43/bd_0f28_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_44/bd_0f28_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_45/bd_0f28_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_47/bd_0f28_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_48/bd_0f28_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_49/bd_0f28_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_50/bd_0f28_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_51/bd_0f28_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/bd_0/ip/ip_52/bd_0f28_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_1/bd_cf79_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_2/bd_cf79_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_3/bd_cf79_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_4/bd_cf79_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_5/bd_cf79_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_6/bd_cf79_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_10/bd_cf79_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_11/bd_cf79_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_12/bd_cf79_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_16/bd_cf79_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_17/bd_cf79_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_18/bd_cf79_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_22/bd_cf79_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_23/bd_cf79_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_24/bd_cf79_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_25/bd_cf79_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_26/bd_cf79_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_27/bd_cf79_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_28/bd_cf79_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_29/bd_cf79_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_30/bd_cf79_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/bd_0/ip/ip_31/bd_cf79_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_smartconnect_1_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/constraints/rdbs_kernel_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_covariance_estimation_0_0/constraints/covariance_estimation_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/constraints/mvdr_weights_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/mvdrr_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/ip_0/bd_48f7_MC0_ddrc_0_phy_ddrmc.elf]
set_property used_in_synthesis false [get_files -all C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/nsln/mvdrr.nts]
set_property used_in_implementation false [get_files -all C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/nsln/mvdrr.nts]
set_property used_in_synthesis false [get_files -all C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/nsln/mvdrr.ncr]
set_property used_in_implementation false [get_files -all C:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/nsln/mvdrr.ncr]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mvdrr_wrapper -part xcvc1902-vsva2197-2MP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mvdrr_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mvdrr_wrapper_utilization_synth.rpt -pb mvdrr_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
