# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xci
# IP: The module: 'mvdrr_clk_wizard_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xci
# IP: The module: 'mvdrr_clk_wizard_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_clk_wizard_0_0/mvdrr_clk_wizard_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_clk_wizard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
