# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xci
# IP: The module: 'mvdrr_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/bd_48f7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7 || ORIG_REF_NAME==bd_48f7} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_0/bd_48f7_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S00_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_1/bd_48f7_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_const_0_0 || ORIG_REF_NAME==bd_48f7_const_0_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_2/bd_48f7_S06_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S06_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_3/bd_48f7_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S01_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_4/bd_48f7_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S02_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_5/bd_48f7_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S03_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_6/bd_48f7_S04_AXI_rpu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_48f7_S04_AXI_rpu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_7/bd_48f7_S05_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S05_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_8/bd_48f7_S07_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S07_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_9/bd_48f7_S08_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S08_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S08_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/bd_48f7_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0 || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/ip_0/bd_48f7_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48f7_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S00_AXI_nmu_0} -quiet] {/bd_48f7_S00_AXI_nmu_0_top_INST } ]/bd_48f7_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48f7_S06_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S06_AXI_nmu_0} -quiet] {/bd_48f7_S06_AXI_nmu_0_top_INST } ]/bd_48f7_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48f7_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S01_AXI_nmu_0} -quiet] {/bd_48f7_S01_AXI_nmu_0_top_INST } ]/bd_48f7_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48f7_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S02_AXI_nmu_0} -quiet] {/bd_48f7_S02_AXI_nmu_0_top_INST } ]/bd_48f7_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_48f7_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S03_AXI_nmu_0} -quiet] {/bd_48f7_S03_AXI_nmu_0_top_INST } ]/bd_48f7_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_48f7_S04_AXI_rpu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_48f7_S04_AXI_rpu_0} -quiet] {/bd_48f7_S04_AXI_rpu_0_top_INST } ]/bd_48f7_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_48f7_S05_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S05_AXI_nmu_0} -quiet] {/bd_48f7_S05_AXI_nmu_0_top_INST } ]/bd_48f7_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_48f7_S07_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S07_AXI_nmu_0} -quiet] {/bd_48f7_S07_AXI_nmu_0_top_INST } ]/bd_48f7_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_9/xdc/bd_48f7_S08_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S08_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S08_AXI_nmu_0} -quiet] {/bd_48f7_S08_AXI_nmu_0_top_INST } ]/bd_48f7_S08_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/hdl/par/bd_48f7_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0 || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xci
# IP: The module: 'mvdrr_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/bd_48f7.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7 || ORIG_REF_NAME==bd_48f7} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_0/bd_48f7_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S00_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_1/bd_48f7_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_const_0_0 || ORIG_REF_NAME==bd_48f7_const_0_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_2/bd_48f7_S06_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S06_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_3/bd_48f7_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S01_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_4/bd_48f7_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S02_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_5/bd_48f7_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S03_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_6/bd_48f7_S04_AXI_rpu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_48f7_S04_AXI_rpu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_7/bd_48f7_S05_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S05_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_8/bd_48f7_S07_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S07_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_9/bd_48f7_S08_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_S08_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S08_AXI_nmu_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/bd_48f7_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0 || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/ip_0/bd_48f7_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48f7_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S00_AXI_nmu_0} -quiet] {/bd_48f7_S00_AXI_nmu_0_top_INST } ]/bd_48f7_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48f7_S06_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S06_AXI_nmu_0} -quiet] {/bd_48f7_S06_AXI_nmu_0_top_INST } ]/bd_48f7_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48f7_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S01_AXI_nmu_0} -quiet] {/bd_48f7_S01_AXI_nmu_0_top_INST } ]/bd_48f7_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48f7_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S02_AXI_nmu_0} -quiet] {/bd_48f7_S02_AXI_nmu_0_top_INST } ]/bd_48f7_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_48f7_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S03_AXI_nmu_0} -quiet] {/bd_48f7_S03_AXI_nmu_0_top_INST } ]/bd_48f7_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_48f7_S04_AXI_rpu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_48f7_S04_AXI_rpu_0} -quiet] {/bd_48f7_S04_AXI_rpu_0_top_INST } ]/bd_48f7_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_48f7_S05_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S05_AXI_nmu_0} -quiet] {/bd_48f7_S05_AXI_nmu_0_top_INST } ]/bd_48f7_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_48f7_S07_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S07_AXI_nmu_0} -quiet] {/bd_48f7_S07_AXI_nmu_0_top_INST } ]/bd_48f7_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_9/xdc/bd_48f7_S08_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_S08_AXI_nmu_0 || ORIG_REF_NAME==bd_48f7_S08_AXI_nmu_0} -quiet] {/bd_48f7_S08_AXI_nmu_0_top_INST } ]/bd_48f7_S08_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/bd_0/ip/ip_10/hdl/par/bd_48f7_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48f7_MC0_ddrc_0 || ORIG_REF_NAME==bd_48f7_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_axi_noc_0_0/mvdrr_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
