# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/mvdrr_mvdr_weights_0_0.xci
# IP: The module: 'mvdrr_mvdr_weights_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip/mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip/mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip/mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip/mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip/mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip/mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip/mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip/mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip/mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip/mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip/mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/constraints/mvdr_weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_mvdr_weights_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/mvdrr_mvdr_weights_0_0.xci
# IP: The module: 'mvdrr_mvdr_weights_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip/mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_dcmp_64ns_64ns_1_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip/mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip/mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fcmp_32ns_32ns_1_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip/mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fdiv_32ns_32ns_32_11_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip/mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmadd_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip/mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmsub_32ns_32ns_32ns_32ns_32_2_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip/mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fmul_32ns_32ns_32_1_primitive_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip/mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip/mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fptrunc_64ns_32_1_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip/mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fsqrt_32ns_32ns_32_15_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/hdl/ip/mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip/mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip || ORIG_REF_NAME==mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_mvdr_weights_0_0/constraints/mvdr_weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_mvdr_weights_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
