// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mvdr_weights_mvdr_weights_Pipeline_NORM_DENOM (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mux_case_0260615,
        mux_case_1262618,
        mux_case_2264621,
        mux_case_3266624,
        mux_case_4268627,
        mux_case_5270630,
        mux_case_6272633,
        mux_case_7274636,
        mux_case_8276639,
        mux_case_9278642,
        mux_case_10280645,
        mux_case_11282648,
        mux_case_12284651,
        mux_case_13286654,
        mux_case_14288657,
        mux_case_15290660,
        mux_case_16292663,
        mux_case_17294666,
        mux_case_18296669,
        mux_case_19298672,
        mux_case_20300675,
        x_r_load,
        x_r_1_load_1,
        x_r_2_load_1,
        x_r_3_load_1,
        x_r_4_load_1,
        x_r_5_load_1,
        x_r_6_load_1,
        x_r_7_load_1,
        x_r_8_load_1,
        x_r_9_load_1,
        x_r_10_load_1,
        x_r_11_load_1,
        x_r_12_load_1,
        x_r_13_load_1,
        x_r_14_load_1,
        x_r_15_load_1,
        x_r_16_load_1,
        x_r_17_load_1,
        x_r_18_load_1,
        x_r_19_load_1,
        x_r_20_load_1,
        mux_case_0344678,
        mux_case_1346681,
        mux_case_2348684,
        mux_case_3350687,
        mux_case_4352690,
        mux_case_5354693,
        mux_case_6356696,
        mux_case_7358699,
        mux_case_8360702,
        mux_case_9362705,
        mux_case_10364708,
        mux_case_11366711,
        mux_case_12368714,
        mux_case_13370717,
        mux_case_14372720,
        mux_case_15374723,
        mux_case_16376726,
        mux_case_17378729,
        mux_case_18380732,
        mux_case_19382735,
        mux_case_20384738,
        x_i_load,
        x_i_1_load_1,
        x_i_2_load_1,
        x_i_3_load_1,
        x_i_4_load_1,
        x_i_5_load_1,
        x_i_6_load_1,
        x_i_7_load_1,
        x_i_8_load_1,
        x_i_9_load_1,
        x_i_10_load_1,
        x_i_11_load_1,
        x_i_12_load_1,
        x_i_13_load_1,
        x_i_14_load_1,
        x_i_15_load_1,
        x_i_16_load_1,
        x_i_17_load_1,
        x_i_18_load_1,
        x_i_19_load_1,
        x_i_20_load_1,
        denom_out,
        denom_out_ap_vld,
        grp_fu_7046_p_din0,
        grp_fu_7046_p_din1,
        grp_fu_7046_p_dout0,
        grp_fu_2069_p_din0,
        grp_fu_2069_p_din1,
        grp_fu_2069_p_din2,
        grp_fu_2069_p_din3,
        grp_fu_2069_p_dout0,
        grp_fu_2069_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mux_case_0260615;
input  [31:0] mux_case_1262618;
input  [31:0] mux_case_2264621;
input  [31:0] mux_case_3266624;
input  [31:0] mux_case_4268627;
input  [31:0] mux_case_5270630;
input  [31:0] mux_case_6272633;
input  [31:0] mux_case_7274636;
input  [31:0] mux_case_8276639;
input  [31:0] mux_case_9278642;
input  [31:0] mux_case_10280645;
input  [31:0] mux_case_11282648;
input  [31:0] mux_case_12284651;
input  [31:0] mux_case_13286654;
input  [31:0] mux_case_14288657;
input  [31:0] mux_case_15290660;
input  [31:0] mux_case_16292663;
input  [31:0] mux_case_17294666;
input  [31:0] mux_case_18296669;
input  [31:0] mux_case_19298672;
input  [31:0] mux_case_20300675;
input  [31:0] x_r_load;
input  [31:0] x_r_1_load_1;
input  [31:0] x_r_2_load_1;
input  [31:0] x_r_3_load_1;
input  [31:0] x_r_4_load_1;
input  [31:0] x_r_5_load_1;
input  [31:0] x_r_6_load_1;
input  [31:0] x_r_7_load_1;
input  [31:0] x_r_8_load_1;
input  [31:0] x_r_9_load_1;
input  [31:0] x_r_10_load_1;
input  [31:0] x_r_11_load_1;
input  [31:0] x_r_12_load_1;
input  [31:0] x_r_13_load_1;
input  [31:0] x_r_14_load_1;
input  [31:0] x_r_15_load_1;
input  [31:0] x_r_16_load_1;
input  [31:0] x_r_17_load_1;
input  [31:0] x_r_18_load_1;
input  [31:0] x_r_19_load_1;
input  [31:0] x_r_20_load_1;
input  [31:0] mux_case_0344678;
input  [31:0] mux_case_1346681;
input  [31:0] mux_case_2348684;
input  [31:0] mux_case_3350687;
input  [31:0] mux_case_4352690;
input  [31:0] mux_case_5354693;
input  [31:0] mux_case_6356696;
input  [31:0] mux_case_7358699;
input  [31:0] mux_case_8360702;
input  [31:0] mux_case_9362705;
input  [31:0] mux_case_10364708;
input  [31:0] mux_case_11366711;
input  [31:0] mux_case_12368714;
input  [31:0] mux_case_13370717;
input  [31:0] mux_case_14372720;
input  [31:0] mux_case_15374723;
input  [31:0] mux_case_16376726;
input  [31:0] mux_case_17378729;
input  [31:0] mux_case_18380732;
input  [31:0] mux_case_19382735;
input  [31:0] mux_case_20384738;
input  [31:0] x_i_load;
input  [31:0] x_i_1_load_1;
input  [31:0] x_i_2_load_1;
input  [31:0] x_i_3_load_1;
input  [31:0] x_i_4_load_1;
input  [31:0] x_i_5_load_1;
input  [31:0] x_i_6_load_1;
input  [31:0] x_i_7_load_1;
input  [31:0] x_i_8_load_1;
input  [31:0] x_i_9_load_1;
input  [31:0] x_i_10_load_1;
input  [31:0] x_i_11_load_1;
input  [31:0] x_i_12_load_1;
input  [31:0] x_i_13_load_1;
input  [31:0] x_i_14_load_1;
input  [31:0] x_i_15_load_1;
input  [31:0] x_i_16_load_1;
input  [31:0] x_i_17_load_1;
input  [31:0] x_i_18_load_1;
input  [31:0] x_i_19_load_1;
input  [31:0] x_i_20_load_1;
output  [31:0] denom_out;
output   denom_out_ap_vld;
output  [31:0] grp_fu_7046_p_din0;
output  [31:0] grp_fu_7046_p_din1;
input  [31:0] grp_fu_7046_p_dout0;
output  [31:0] grp_fu_2069_p_din0;
output  [31:0] grp_fu_2069_p_din1;
output  [31:0] grp_fu_2069_p_din2;
output  [31:0] grp_fu_2069_p_din3;
input  [31:0] grp_fu_2069_p_dout0;
output   grp_fu_2069_p_ce;

reg ap_idle;
reg denom_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln237_fu_795_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln237_reg_1226;
reg   [0:0] icmp_ln237_reg_1226_pp0_iter1_reg;
reg   [0:0] icmp_ln237_reg_1226_pp0_iter2_reg;
reg   [0:0] icmp_ln237_reg_1226_pp0_iter3_reg;
reg   [0:0] icmp_ln237_reg_1226_pp0_iter4_reg;
wire   [31:0] tmp_11_fu_801_p45;
reg   [31:0] tmp_11_reg_1230;
reg   [31:0] tmp_11_reg_1230_pp0_iter1_reg;
wire   [31:0] tmp_s_fu_893_p45;
reg   [31:0] tmp_s_reg_1236;
reg   [31:0] tmp_s_reg_1236_pp0_iter1_reg;
wire   [31:0] tmp_12_fu_985_p45;
wire   [31:0] tmp_13_fu_1077_p45;
wire   [0:0] icmp_ln239_fu_1177_p2;
reg   [0:0] icmp_ln239_reg_1252;
reg   [0:0] icmp_ln239_reg_1252_pp0_iter1_reg;
reg   [0:0] icmp_ln239_reg_1252_pp0_iter2_reg;
reg   [0:0] icmp_ln239_reg_1252_pp0_iter3_reg;
reg   [0:0] icmp_ln239_reg_1252_pp0_iter4_reg;
reg   [31:0] mul7_reg_1257;
reg   [31:0] add_reg_1263;
reg   [31:0] denom_fu_246;
wire   [31:0] grp_fu_1197_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [4:0] i_fu_250;
wire   [4:0] add_ln237_fu_789_p2;
reg   [4:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0_01001;
reg   [31:0] grp_fu_765_p0;
reg   [31:0] grp_fu_765_p0_keep;
reg   [31:0] grp_fu_765_p1;
reg   [31:0] grp_fu_765_p1_keep;
wire   [31:0] tmp_11_fu_801_p43;
wire   [31:0] tmp_s_fu_893_p43;
wire   [31:0] tmp_12_fu_985_p43;
wire   [31:0] tmp_13_fu_1077_p43;
reg   [31:0] grp_fu_1197_p1;
reg   [0:0] grp_fu_1197_p2;
reg    grp_fu_1197_in_valid;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_11_fu_801_p1;
wire   [4:0] tmp_11_fu_801_p3;
wire   [4:0] tmp_11_fu_801_p5;
wire   [4:0] tmp_11_fu_801_p7;
wire   [4:0] tmp_11_fu_801_p9;
wire   [4:0] tmp_11_fu_801_p11;
wire   [4:0] tmp_11_fu_801_p13;
wire   [4:0] tmp_11_fu_801_p15;
wire   [4:0] tmp_11_fu_801_p17;
wire   [4:0] tmp_11_fu_801_p19;
wire   [4:0] tmp_11_fu_801_p21;
wire   [4:0] tmp_11_fu_801_p23;
wire   [4:0] tmp_11_fu_801_p25;
wire   [4:0] tmp_11_fu_801_p27;
wire   [4:0] tmp_11_fu_801_p29;
wire   [4:0] tmp_11_fu_801_p31;
wire  signed [4:0] tmp_11_fu_801_p33;
wire  signed [4:0] tmp_11_fu_801_p35;
wire  signed [4:0] tmp_11_fu_801_p37;
wire  signed [4:0] tmp_11_fu_801_p39;
wire  signed [4:0] tmp_11_fu_801_p41;
wire   [4:0] tmp_s_fu_893_p1;
wire   [4:0] tmp_s_fu_893_p3;
wire   [4:0] tmp_s_fu_893_p5;
wire   [4:0] tmp_s_fu_893_p7;
wire   [4:0] tmp_s_fu_893_p9;
wire   [4:0] tmp_s_fu_893_p11;
wire   [4:0] tmp_s_fu_893_p13;
wire   [4:0] tmp_s_fu_893_p15;
wire   [4:0] tmp_s_fu_893_p17;
wire   [4:0] tmp_s_fu_893_p19;
wire   [4:0] tmp_s_fu_893_p21;
wire   [4:0] tmp_s_fu_893_p23;
wire   [4:0] tmp_s_fu_893_p25;
wire   [4:0] tmp_s_fu_893_p27;
wire   [4:0] tmp_s_fu_893_p29;
wire   [4:0] tmp_s_fu_893_p31;
wire  signed [4:0] tmp_s_fu_893_p33;
wire  signed [4:0] tmp_s_fu_893_p35;
wire  signed [4:0] tmp_s_fu_893_p37;
wire  signed [4:0] tmp_s_fu_893_p39;
wire  signed [4:0] tmp_s_fu_893_p41;
wire   [4:0] tmp_12_fu_985_p1;
wire   [4:0] tmp_12_fu_985_p3;
wire   [4:0] tmp_12_fu_985_p5;
wire   [4:0] tmp_12_fu_985_p7;
wire   [4:0] tmp_12_fu_985_p9;
wire   [4:0] tmp_12_fu_985_p11;
wire   [4:0] tmp_12_fu_985_p13;
wire   [4:0] tmp_12_fu_985_p15;
wire   [4:0] tmp_12_fu_985_p17;
wire   [4:0] tmp_12_fu_985_p19;
wire   [4:0] tmp_12_fu_985_p21;
wire   [4:0] tmp_12_fu_985_p23;
wire   [4:0] tmp_12_fu_985_p25;
wire   [4:0] tmp_12_fu_985_p27;
wire   [4:0] tmp_12_fu_985_p29;
wire   [4:0] tmp_12_fu_985_p31;
wire  signed [4:0] tmp_12_fu_985_p33;
wire  signed [4:0] tmp_12_fu_985_p35;
wire  signed [4:0] tmp_12_fu_985_p37;
wire  signed [4:0] tmp_12_fu_985_p39;
wire  signed [4:0] tmp_12_fu_985_p41;
wire   [4:0] tmp_13_fu_1077_p1;
wire   [4:0] tmp_13_fu_1077_p3;
wire   [4:0] tmp_13_fu_1077_p5;
wire   [4:0] tmp_13_fu_1077_p7;
wire   [4:0] tmp_13_fu_1077_p9;
wire   [4:0] tmp_13_fu_1077_p11;
wire   [4:0] tmp_13_fu_1077_p13;
wire   [4:0] tmp_13_fu_1077_p15;
wire   [4:0] tmp_13_fu_1077_p17;
wire   [4:0] tmp_13_fu_1077_p19;
wire   [4:0] tmp_13_fu_1077_p21;
wire   [4:0] tmp_13_fu_1077_p23;
wire   [4:0] tmp_13_fu_1077_p25;
wire   [4:0] tmp_13_fu_1077_p27;
wire   [4:0] tmp_13_fu_1077_p29;
wire   [4:0] tmp_13_fu_1077_p31;
wire  signed [4:0] tmp_13_fu_1077_p33;
wire  signed [4:0] tmp_13_fu_1077_p35;
wire  signed [4:0] tmp_13_fu_1077_p37;
wire  signed [4:0] tmp_13_fu_1077_p39;
wire  signed [4:0] tmp_13_fu_1077_p41;
wire   [31:0] grp_fu_1197_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 denom_fu_246 = 32'd0;
#0 i_fu_250 = 5'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U288(
    .din0(mux_case_0260615),
    .din1(mux_case_1262618),
    .din2(mux_case_2264621),
    .din3(mux_case_3266624),
    .din4(mux_case_4268627),
    .din5(mux_case_5270630),
    .din6(mux_case_6272633),
    .din7(mux_case_7274636),
    .din8(mux_case_8276639),
    .din9(mux_case_9278642),
    .din10(mux_case_10280645),
    .din11(mux_case_11282648),
    .din12(mux_case_12284651),
    .din13(mux_case_13286654),
    .din14(mux_case_14288657),
    .din15(mux_case_15290660),
    .din16(mux_case_16292663),
    .din17(mux_case_17294666),
    .din18(mux_case_18296669),
    .din19(mux_case_19298672),
    .din20(mux_case_20300675),
    .def(tmp_11_fu_801_p43),
    .sel(ap_sig_allocacmp_i_2),
    .dout(tmp_11_fu_801_p45)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U289(
    .din0(x_r_load),
    .din1(x_r_1_load_1),
    .din2(x_r_2_load_1),
    .din3(x_r_3_load_1),
    .din4(x_r_4_load_1),
    .din5(x_r_5_load_1),
    .din6(x_r_6_load_1),
    .din7(x_r_7_load_1),
    .din8(x_r_8_load_1),
    .din9(x_r_9_load_1),
    .din10(x_r_10_load_1),
    .din11(x_r_11_load_1),
    .din12(x_r_12_load_1),
    .din13(x_r_13_load_1),
    .din14(x_r_14_load_1),
    .din15(x_r_15_load_1),
    .din16(x_r_16_load_1),
    .din17(x_r_17_load_1),
    .din18(x_r_18_load_1),
    .din19(x_r_19_load_1),
    .din20(x_r_20_load_1),
    .def(tmp_s_fu_893_p43),
    .sel(ap_sig_allocacmp_i_2),
    .dout(tmp_s_fu_893_p45)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U290(
    .din0(mux_case_0344678),
    .din1(mux_case_1346681),
    .din2(mux_case_2348684),
    .din3(mux_case_3350687),
    .din4(mux_case_4352690),
    .din5(mux_case_5354693),
    .din6(mux_case_6356696),
    .din7(mux_case_7358699),
    .din8(mux_case_8360702),
    .din9(mux_case_9362705),
    .din10(mux_case_10364708),
    .din11(mux_case_11366711),
    .din12(mux_case_12368714),
    .din13(mux_case_13370717),
    .din14(mux_case_14372720),
    .din15(mux_case_15374723),
    .din16(mux_case_16376726),
    .din17(mux_case_17378729),
    .din18(mux_case_18380732),
    .din19(mux_case_19382735),
    .din20(mux_case_20384738),
    .def(tmp_12_fu_985_p43),
    .sel(ap_sig_allocacmp_i_2),
    .dout(tmp_12_fu_985_p45)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U291(
    .din0(x_i_load),
    .din1(x_i_1_load_1),
    .din2(x_i_2_load_1),
    .din3(x_i_3_load_1),
    .din4(x_i_4_load_1),
    .din5(x_i_5_load_1),
    .din6(x_i_6_load_1),
    .din7(x_i_7_load_1),
    .din8(x_i_8_load_1),
    .din9(x_i_9_load_1),
    .din10(x_i_10_load_1),
    .din11(x_i_11_load_1),
    .din12(x_i_12_load_1),
    .din13(x_i_13_load_1),
    .din14(x_i_14_load_1),
    .din15(x_i_15_load_1),
    .din16(x_i_16_load_1),
    .din17(x_i_17_load_1),
    .din18(x_i_18_load_1),
    .din19(x_i_19_load_1),
    .din20(x_i_20_load_1),
    .def(tmp_13_fu_1077_p43),
    .sel(ap_sig_allocacmp_i_2),
    .dout(tmp_13_fu_1077_p45)
);

mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .DWIDTH( 32 ),
    .OUTPUT_DATA_WIDTH( 32 ))
facc_32ns_32ns_1ns_32_2_primitive_dsp_1_U292(
    .clk(ap_clk),
    .reset(ap_rst),
    .ce(1'b1),
    .in_data(grp_fu_1197_p1),
    .in_last(grp_fu_1197_p2),
    .in_valid(grp_fu_1197_in_valid),
    .out_data(grp_fu_1197_p3)
);

mvdr_weights_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            denom_fu_246 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            denom_fu_246 <= grp_fu_1197_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln237_fu_795_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_250 <= add_ln237_fu_789_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_250 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_reg_1263 <= grp_fu_2069_p_dout0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln237_reg_1226_pp0_iter2_reg <= icmp_ln237_reg_1226_pp0_iter1_reg;
        icmp_ln237_reg_1226_pp0_iter3_reg <= icmp_ln237_reg_1226_pp0_iter2_reg;
        icmp_ln237_reg_1226_pp0_iter4_reg <= icmp_ln237_reg_1226_pp0_iter3_reg;
        icmp_ln239_reg_1252_pp0_iter2_reg <= icmp_ln239_reg_1252_pp0_iter1_reg;
        icmp_ln239_reg_1252_pp0_iter3_reg <= icmp_ln239_reg_1252_pp0_iter2_reg;
        icmp_ln239_reg_1252_pp0_iter4_reg <= icmp_ln239_reg_1252_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln237_reg_1226 <= icmp_ln237_fu_795_p2;
        icmp_ln237_reg_1226_pp0_iter1_reg <= icmp_ln237_reg_1226;
        icmp_ln239_reg_1252 <= icmp_ln239_fu_1177_p2;
        icmp_ln239_reg_1252_pp0_iter1_reg <= icmp_ln239_reg_1252;
        mul7_reg_1257 <= grp_fu_7046_p_dout0;
        tmp_11_reg_1230 <= tmp_11_fu_801_p45;
        tmp_11_reg_1230_pp0_iter1_reg <= tmp_11_reg_1230;
        tmp_s_reg_1236 <= tmp_s_fu_893_p45;
        tmp_s_reg_1236_pp0_iter1_reg <= tmp_s_reg_1236;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_fu_795_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_765_p0_keep <= tmp_12_fu_985_p45;
        grp_fu_765_p1_keep <= tmp_13_fu_1077_p45;
    end
end

always @ (*) begin
    if (((icmp_ln237_fu_795_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_250;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln237_reg_1226_pp0_iter4_reg == 1'd1))) begin
        denom_out_ap_vld = 1'b1;
    end else begin
        denom_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_1197_in_valid = 1'b1;
    end else begin
        grp_fu_1197_in_valid = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_1197_p1 = add_reg_1263;
    end else begin
        grp_fu_1197_p1 = 32'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_1197_p2 = icmp_ln239_reg_1252_pp0_iter4_reg;
    end else begin
        grp_fu_1197_p2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln237_fu_795_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_765_p0 = tmp_12_fu_985_p45;
    end else begin
        grp_fu_765_p0 = grp_fu_765_p0_keep;
    end
end

always @ (*) begin
    if (((icmp_ln237_fu_795_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_765_p1 = tmp_13_fu_1077_p45;
    end else begin
        grp_fu_765_p1 = grp_fu_765_p1_keep;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln237_fu_789_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign denom_out = denom_fu_246;

assign grp_fu_2069_p_ce = 1'b1;

assign grp_fu_2069_p_din0 = 32'd0;

assign grp_fu_2069_p_din1 = tmp_11_reg_1230_pp0_iter1_reg;

assign grp_fu_2069_p_din2 = tmp_s_reg_1236_pp0_iter1_reg;

assign grp_fu_2069_p_din3 = mul7_reg_1257;

assign grp_fu_7046_p_din0 = grp_fu_765_p0;

assign grp_fu_7046_p_din1 = grp_fu_765_p1;

assign icmp_ln237_fu_795_p2 = ((ap_sig_allocacmp_i_2 == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_1177_p2 = ((add_ln237_fu_789_p2 == 5'd21) ? 1'b1 : 1'b0);

assign tmp_11_fu_801_p43 = 'bx;

assign tmp_12_fu_985_p43 = 'bx;

assign tmp_13_fu_1077_p43 = 'bx;

assign tmp_s_fu_893_p43 = 'bx;

endmodule //mvdr_weights_mvdr_weights_Pipeline_NORM_DENOM
