// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mvdr_weights_mvdr_weights_Pipeline_BACK_SUB_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln198_1,
        acc_re,
        acc_im,
        A_r_address0,
        A_r_ce0,
        A_r_q0,
        A_r_1_address0,
        A_r_1_ce0,
        A_r_1_q0,
        A_r_2_address0,
        A_r_2_ce0,
        A_r_2_q0,
        A_r_3_address0,
        A_r_3_ce0,
        A_r_3_q0,
        A_r_4_address0,
        A_r_4_ce0,
        A_r_4_q0,
        A_r_5_address0,
        A_r_5_ce0,
        A_r_5_q0,
        A_r_6_address0,
        A_r_6_ce0,
        A_r_6_q0,
        A_r_7_address0,
        A_r_7_ce0,
        A_r_7_q0,
        A_r_8_address0,
        A_r_8_ce0,
        A_r_8_q0,
        A_r_9_address0,
        A_r_9_ce0,
        A_r_9_q0,
        A_r_10_address0,
        A_r_10_ce0,
        A_r_10_q0,
        A_r_11_address0,
        A_r_11_ce0,
        A_r_11_q0,
        A_r_12_address0,
        A_r_12_ce0,
        A_r_12_q0,
        A_r_13_address0,
        A_r_13_ce0,
        A_r_13_q0,
        A_r_14_address0,
        A_r_14_ce0,
        A_r_14_q0,
        A_r_15_address0,
        A_r_15_ce0,
        A_r_15_q0,
        A_r_16_address0,
        A_r_16_ce0,
        A_r_16_q0,
        A_r_17_address0,
        A_r_17_ce0,
        A_r_17_q0,
        A_r_18_address0,
        A_r_18_ce0,
        A_r_18_q0,
        A_r_19_address0,
        A_r_19_ce0,
        A_r_19_q0,
        A_r_20_address0,
        A_r_20_ce0,
        A_r_20_q0,
        empty,
        x_r_1_load,
        x_r_2_load,
        x_r_3_load,
        x_r_4_load,
        x_r_5_load,
        x_r_6_load,
        x_r_7_load,
        x_r_8_load,
        x_r_9_load,
        x_r_10_load,
        x_r_11_load,
        x_r_12_load,
        x_r_13_load,
        x_r_14_load,
        x_r_15_load,
        x_r_16_load,
        x_r_17_load,
        x_r_18_load,
        x_r_19_load,
        x_r_20_load,
        A_i_address0,
        A_i_ce0,
        A_i_q0,
        A_i_1_address0,
        A_i_1_ce0,
        A_i_1_q0,
        A_i_2_address0,
        A_i_2_ce0,
        A_i_2_q0,
        A_i_3_address0,
        A_i_3_ce0,
        A_i_3_q0,
        A_i_4_address0,
        A_i_4_ce0,
        A_i_4_q0,
        A_i_5_address0,
        A_i_5_ce0,
        A_i_5_q0,
        A_i_6_address0,
        A_i_6_ce0,
        A_i_6_q0,
        A_i_7_address0,
        A_i_7_ce0,
        A_i_7_q0,
        A_i_8_address0,
        A_i_8_ce0,
        A_i_8_q0,
        A_i_9_address0,
        A_i_9_ce0,
        A_i_9_q0,
        A_i_10_address0,
        A_i_10_ce0,
        A_i_10_q0,
        A_i_11_address0,
        A_i_11_ce0,
        A_i_11_q0,
        A_i_12_address0,
        A_i_12_ce0,
        A_i_12_q0,
        A_i_13_address0,
        A_i_13_ce0,
        A_i_13_q0,
        A_i_14_address0,
        A_i_14_ce0,
        A_i_14_q0,
        A_i_15_address0,
        A_i_15_ce0,
        A_i_15_q0,
        A_i_16_address0,
        A_i_16_ce0,
        A_i_16_q0,
        A_i_17_address0,
        A_i_17_ce0,
        A_i_17_q0,
        A_i_18_address0,
        A_i_18_ce0,
        A_i_18_q0,
        A_i_19_address0,
        A_i_19_ce0,
        A_i_19_q0,
        A_i_20_address0,
        A_i_20_ce0,
        A_i_20_q0,
        x_i_1_load,
        x_i_2_load,
        x_i_3_load,
        x_i_4_load,
        x_i_5_load,
        x_i_6_load,
        x_i_7_load,
        x_i_8_load,
        x_i_9_load,
        x_i_10_load,
        x_i_11_load,
        x_i_12_load,
        x_i_13_load,
        x_i_14_load,
        x_i_15_load,
        x_i_16_load,
        x_i_17_load,
        x_i_18_load,
        x_i_19_load,
        x_i_20_load,
        acc_re_1_out,
        acc_re_1_out_ap_vld,
        acc_im_1_out,
        acc_im_1_out_ap_vld,
        grp_fu_7042_p_din0,
        grp_fu_7042_p_din1,
        grp_fu_7042_p_dout0,
        grp_fu_7046_p_din0,
        grp_fu_7046_p_din1,
        grp_fu_7046_p_dout0,
        grp_fu_2069_p_din0,
        grp_fu_2069_p_din1,
        grp_fu_2069_p_din2,
        grp_fu_2069_p_din3,
        grp_fu_2069_p_dout0,
        grp_fu_2069_p_ce,
        grp_fu_2077_p_din0,
        grp_fu_2077_p_din1,
        grp_fu_2077_p_din2,
        grp_fu_2077_p_din3,
        grp_fu_2077_p_dout0,
        grp_fu_2077_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] zext_ln198_1;
input  [31:0] acc_re;
input  [31:0] acc_im;
output  [4:0] A_r_address0;
output   A_r_ce0;
input  [31:0] A_r_q0;
output  [4:0] A_r_1_address0;
output   A_r_1_ce0;
input  [31:0] A_r_1_q0;
output  [4:0] A_r_2_address0;
output   A_r_2_ce0;
input  [31:0] A_r_2_q0;
output  [4:0] A_r_3_address0;
output   A_r_3_ce0;
input  [31:0] A_r_3_q0;
output  [4:0] A_r_4_address0;
output   A_r_4_ce0;
input  [31:0] A_r_4_q0;
output  [4:0] A_r_5_address0;
output   A_r_5_ce0;
input  [31:0] A_r_5_q0;
output  [4:0] A_r_6_address0;
output   A_r_6_ce0;
input  [31:0] A_r_6_q0;
output  [4:0] A_r_7_address0;
output   A_r_7_ce0;
input  [31:0] A_r_7_q0;
output  [4:0] A_r_8_address0;
output   A_r_8_ce0;
input  [31:0] A_r_8_q0;
output  [4:0] A_r_9_address0;
output   A_r_9_ce0;
input  [31:0] A_r_9_q0;
output  [4:0] A_r_10_address0;
output   A_r_10_ce0;
input  [31:0] A_r_10_q0;
output  [4:0] A_r_11_address0;
output   A_r_11_ce0;
input  [31:0] A_r_11_q0;
output  [4:0] A_r_12_address0;
output   A_r_12_ce0;
input  [31:0] A_r_12_q0;
output  [4:0] A_r_13_address0;
output   A_r_13_ce0;
input  [31:0] A_r_13_q0;
output  [4:0] A_r_14_address0;
output   A_r_14_ce0;
input  [31:0] A_r_14_q0;
output  [4:0] A_r_15_address0;
output   A_r_15_ce0;
input  [31:0] A_r_15_q0;
output  [4:0] A_r_16_address0;
output   A_r_16_ce0;
input  [31:0] A_r_16_q0;
output  [4:0] A_r_17_address0;
output   A_r_17_ce0;
input  [31:0] A_r_17_q0;
output  [4:0] A_r_18_address0;
output   A_r_18_ce0;
input  [31:0] A_r_18_q0;
output  [4:0] A_r_19_address0;
output   A_r_19_ce0;
input  [31:0] A_r_19_q0;
output  [4:0] A_r_20_address0;
output   A_r_20_ce0;
input  [31:0] A_r_20_q0;
input  [4:0] empty;
input  [31:0] x_r_1_load;
input  [31:0] x_r_2_load;
input  [31:0] x_r_3_load;
input  [31:0] x_r_4_load;
input  [31:0] x_r_5_load;
input  [31:0] x_r_6_load;
input  [31:0] x_r_7_load;
input  [31:0] x_r_8_load;
input  [31:0] x_r_9_load;
input  [31:0] x_r_10_load;
input  [31:0] x_r_11_load;
input  [31:0] x_r_12_load;
input  [31:0] x_r_13_load;
input  [31:0] x_r_14_load;
input  [31:0] x_r_15_load;
input  [31:0] x_r_16_load;
input  [31:0] x_r_17_load;
input  [31:0] x_r_18_load;
input  [31:0] x_r_19_load;
input  [31:0] x_r_20_load;
output  [4:0] A_i_address0;
output   A_i_ce0;
input  [31:0] A_i_q0;
output  [4:0] A_i_1_address0;
output   A_i_1_ce0;
input  [31:0] A_i_1_q0;
output  [4:0] A_i_2_address0;
output   A_i_2_ce0;
input  [31:0] A_i_2_q0;
output  [4:0] A_i_3_address0;
output   A_i_3_ce0;
input  [31:0] A_i_3_q0;
output  [4:0] A_i_4_address0;
output   A_i_4_ce0;
input  [31:0] A_i_4_q0;
output  [4:0] A_i_5_address0;
output   A_i_5_ce0;
input  [31:0] A_i_5_q0;
output  [4:0] A_i_6_address0;
output   A_i_6_ce0;
input  [31:0] A_i_6_q0;
output  [4:0] A_i_7_address0;
output   A_i_7_ce0;
input  [31:0] A_i_7_q0;
output  [4:0] A_i_8_address0;
output   A_i_8_ce0;
input  [31:0] A_i_8_q0;
output  [4:0] A_i_9_address0;
output   A_i_9_ce0;
input  [31:0] A_i_9_q0;
output  [4:0] A_i_10_address0;
output   A_i_10_ce0;
input  [31:0] A_i_10_q0;
output  [4:0] A_i_11_address0;
output   A_i_11_ce0;
input  [31:0] A_i_11_q0;
output  [4:0] A_i_12_address0;
output   A_i_12_ce0;
input  [31:0] A_i_12_q0;
output  [4:0] A_i_13_address0;
output   A_i_13_ce0;
input  [31:0] A_i_13_q0;
output  [4:0] A_i_14_address0;
output   A_i_14_ce0;
input  [31:0] A_i_14_q0;
output  [4:0] A_i_15_address0;
output   A_i_15_ce0;
input  [31:0] A_i_15_q0;
output  [4:0] A_i_16_address0;
output   A_i_16_ce0;
input  [31:0] A_i_16_q0;
output  [4:0] A_i_17_address0;
output   A_i_17_ce0;
input  [31:0] A_i_17_q0;
output  [4:0] A_i_18_address0;
output   A_i_18_ce0;
input  [31:0] A_i_18_q0;
output  [4:0] A_i_19_address0;
output   A_i_19_ce0;
input  [31:0] A_i_19_q0;
output  [4:0] A_i_20_address0;
output   A_i_20_ce0;
input  [31:0] A_i_20_q0;
input  [31:0] x_i_1_load;
input  [31:0] x_i_2_load;
input  [31:0] x_i_3_load;
input  [31:0] x_i_4_load;
input  [31:0] x_i_5_load;
input  [31:0] x_i_6_load;
input  [31:0] x_i_7_load;
input  [31:0] x_i_8_load;
input  [31:0] x_i_9_load;
input  [31:0] x_i_10_load;
input  [31:0] x_i_11_load;
input  [31:0] x_i_12_load;
input  [31:0] x_i_13_load;
input  [31:0] x_i_14_load;
input  [31:0] x_i_15_load;
input  [31:0] x_i_16_load;
input  [31:0] x_i_17_load;
input  [31:0] x_i_18_load;
input  [31:0] x_i_19_load;
input  [31:0] x_i_20_load;
output  [31:0] acc_re_1_out;
output   acc_re_1_out_ap_vld;
output  [31:0] acc_im_1_out;
output   acc_im_1_out_ap_vld;
output  [31:0] grp_fu_7042_p_din0;
output  [31:0] grp_fu_7042_p_din1;
input  [31:0] grp_fu_7042_p_dout0;
output  [31:0] grp_fu_7046_p_din0;
output  [31:0] grp_fu_7046_p_din1;
input  [31:0] grp_fu_7046_p_dout0;
output  [31:0] grp_fu_2069_p_din0;
output  [31:0] grp_fu_2069_p_din1;
output  [31:0] grp_fu_2069_p_din2;
output  [31:0] grp_fu_2069_p_din3;
input  [31:0] grp_fu_2069_p_dout0;
output   grp_fu_2069_p_ce;
output  [31:0] grp_fu_2077_p_din0;
output  [31:0] grp_fu_2077_p_din1;
output  [31:0] grp_fu_2077_p_din2;
output  [31:0] grp_fu_2077_p_din3;
input  [31:0] grp_fu_2077_p_dout0;
output   grp_fu_2077_p_ce;

reg ap_idle;
reg acc_re_1_out_ap_vld;
reg acc_im_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln204_fu_1148_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] tmp_read_fu_512_p2;
wire   [4:0] tmp_reg_1817;
reg   [0:0] icmp_ln204_reg_1823;
reg   [0:0] icmp_ln204_reg_1823_pp0_iter1_reg;
reg   [0:0] icmp_ln204_reg_1823_pp0_iter2_reg;
reg   [0:0] icmp_ln204_reg_1823_pp0_iter3_reg;
reg   [0:0] icmp_ln204_reg_1823_pp0_iter4_reg;
wire   [63:0] zext_ln204_fu_1154_p1;
reg   [63:0] zext_ln204_reg_1827;
reg   [63:0] zext_ln204_reg_1827_pp0_iter1_reg;
wire   [31:0] tmp_4_fu_1183_p43;
reg   [31:0] tmp_4_reg_1852;
reg   [31:0] tmp_4_reg_1852_pp0_iter1_reg;
reg   [31:0] tmp_4_reg_1852_pp0_iter2_reg;
wire   [31:0] tmp_10_fu_1355_p43;
reg   [31:0] tmp_10_reg_1965;
reg   [31:0] tmp_10_reg_1965_pp0_iter1_reg;
reg   [31:0] tmp_10_reg_1965_pp0_iter2_reg;
wire   [31:0] tmp_5_fu_1454_p45;
reg   [31:0] mul3_reg_2084;
reg   [31:0] mul5_reg_2090;
wire   [31:0] tmp_s_fu_1643_p45;
reg   [31:0] sub_reg_2102;
reg   [31:0] add_reg_2108;
wire    ap_block_pp0_stage0;
reg    ap_predicate_pred603_state3;
reg    ap_predicate_pred607_state3;
reg    ap_predicate_pred611_state3;
reg    ap_predicate_pred615_state3;
reg    ap_predicate_pred619_state3;
reg    ap_predicate_pred623_state3;
reg    ap_predicate_pred627_state3;
reg    ap_predicate_pred631_state3;
reg    ap_predicate_pred635_state3;
reg    ap_predicate_pred639_state3;
reg    ap_predicate_pred643_state3;
reg    ap_predicate_pred647_state3;
reg    ap_predicate_pred651_state3;
reg    ap_predicate_pred655_state3;
reg    ap_predicate_pred659_state3;
reg    ap_predicate_pred663_state3;
reg    ap_predicate_pred667_state3;
reg    ap_predicate_pred671_state3;
reg    ap_predicate_pred675_state3;
reg    ap_predicate_pred679_state3;
reg    ap_predicate_pred683_state3;
reg   [31:0] acc_im_1_fu_260;
wire   [31:0] acc_im_2_fu_1100_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [31:0] acc_re_1_fu_264;
wire   [31:0] acc_re_2_fu_1096_p2;
reg   [5:0] j_1_fu_268;
wire   [5:0] zext_ln198_1_cast_fu_1126_p1;
wire   [5:0] add_ln204_fu_1443_p2;
reg   [5:0] ap_sig_allocacmp_j;
wire    ap_block_pp0_stage0_01001;
reg    A_i_ce0_local;
reg    A_i_1_ce0_local;
reg    A_i_2_ce0_local;
reg    A_i_3_ce0_local;
reg    A_i_4_ce0_local;
reg    A_i_5_ce0_local;
reg    A_i_6_ce0_local;
reg    A_i_7_ce0_local;
reg    A_i_8_ce0_local;
reg    A_i_9_ce0_local;
reg    A_i_10_ce0_local;
reg    A_i_11_ce0_local;
reg    A_i_12_ce0_local;
reg    A_i_13_ce0_local;
reg    A_i_14_ce0_local;
reg    A_i_15_ce0_local;
reg    A_i_16_ce0_local;
reg    A_i_17_ce0_local;
reg    A_i_18_ce0_local;
reg    A_i_19_ce0_local;
reg    A_i_20_ce0_local;
reg    A_r_ce0_local;
reg    A_r_1_ce0_local;
reg    A_r_2_ce0_local;
reg    A_r_3_ce0_local;
reg    A_r_4_ce0_local;
reg    A_r_5_ce0_local;
reg    A_r_6_ce0_local;
reg    A_r_7_ce0_local;
reg    A_r_8_ce0_local;
reg    A_r_9_ce0_local;
reg    A_r_10_ce0_local;
reg    A_r_11_ce0_local;
reg    A_r_12_ce0_local;
reg    A_r_13_ce0_local;
reg    A_r_14_ce0_local;
reg    A_r_15_ce0_local;
reg    A_r_16_ce0_local;
reg    A_r_17_ce0_local;
reg    A_r_18_ce0_local;
reg    A_r_19_ce0_local;
reg    A_r_20_ce0_local;
reg   [31:0] grp_fu_1104_p0;
reg   [31:0] grp_fu_1104_p0_keep;
reg   [31:0] grp_fu_1104_p1;
reg   [31:0] grp_fu_1104_p1_keep;
reg   [31:0] grp_fu_1108_p0;
reg   [31:0] grp_fu_1108_p0_keep;
reg   [31:0] grp_fu_1108_p1;
reg   [31:0] grp_fu_1108_p1_keep;
wire   [31:0] tmp_4_fu_1183_p41;
wire   [4:0] trunc_ln204_fu_1179_p1;
wire   [31:0] tmp_10_fu_1355_p41;
wire   [31:0] tmp_5_fu_1454_p43;
wire   [31:0] tmp_s_fu_1643_p43;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_4_fu_1183_p1;
wire   [4:0] tmp_4_fu_1183_p3;
wire   [4:0] tmp_4_fu_1183_p5;
wire   [4:0] tmp_4_fu_1183_p7;
wire   [4:0] tmp_4_fu_1183_p9;
wire   [4:0] tmp_4_fu_1183_p11;
wire   [4:0] tmp_4_fu_1183_p13;
wire   [4:0] tmp_4_fu_1183_p15;
wire   [4:0] tmp_4_fu_1183_p17;
wire   [4:0] tmp_4_fu_1183_p19;
wire   [4:0] tmp_4_fu_1183_p21;
wire   [4:0] tmp_4_fu_1183_p23;
wire   [4:0] tmp_4_fu_1183_p25;
wire   [4:0] tmp_4_fu_1183_p27;
wire   [4:0] tmp_4_fu_1183_p29;
wire  signed [4:0] tmp_4_fu_1183_p31;
wire  signed [4:0] tmp_4_fu_1183_p33;
wire  signed [4:0] tmp_4_fu_1183_p35;
wire  signed [4:0] tmp_4_fu_1183_p37;
wire  signed [4:0] tmp_4_fu_1183_p39;
wire   [4:0] tmp_10_fu_1355_p1;
wire   [4:0] tmp_10_fu_1355_p3;
wire   [4:0] tmp_10_fu_1355_p5;
wire   [4:0] tmp_10_fu_1355_p7;
wire   [4:0] tmp_10_fu_1355_p9;
wire   [4:0] tmp_10_fu_1355_p11;
wire   [4:0] tmp_10_fu_1355_p13;
wire   [4:0] tmp_10_fu_1355_p15;
wire   [4:0] tmp_10_fu_1355_p17;
wire   [4:0] tmp_10_fu_1355_p19;
wire   [4:0] tmp_10_fu_1355_p21;
wire   [4:0] tmp_10_fu_1355_p23;
wire   [4:0] tmp_10_fu_1355_p25;
wire   [4:0] tmp_10_fu_1355_p27;
wire   [4:0] tmp_10_fu_1355_p29;
wire  signed [4:0] tmp_10_fu_1355_p31;
wire  signed [4:0] tmp_10_fu_1355_p33;
wire  signed [4:0] tmp_10_fu_1355_p35;
wire  signed [4:0] tmp_10_fu_1355_p37;
wire  signed [4:0] tmp_10_fu_1355_p39;
wire   [4:0] tmp_5_fu_1454_p1;
wire   [4:0] tmp_5_fu_1454_p3;
wire   [4:0] tmp_5_fu_1454_p5;
wire   [4:0] tmp_5_fu_1454_p7;
wire   [4:0] tmp_5_fu_1454_p9;
wire   [4:0] tmp_5_fu_1454_p11;
wire   [4:0] tmp_5_fu_1454_p13;
wire   [4:0] tmp_5_fu_1454_p15;
wire   [4:0] tmp_5_fu_1454_p17;
wire   [4:0] tmp_5_fu_1454_p19;
wire   [4:0] tmp_5_fu_1454_p21;
wire   [4:0] tmp_5_fu_1454_p23;
wire   [4:0] tmp_5_fu_1454_p25;
wire   [4:0] tmp_5_fu_1454_p27;
wire   [4:0] tmp_5_fu_1454_p29;
wire   [4:0] tmp_5_fu_1454_p31;
wire  signed [4:0] tmp_5_fu_1454_p33;
wire  signed [4:0] tmp_5_fu_1454_p35;
wire  signed [4:0] tmp_5_fu_1454_p37;
wire  signed [4:0] tmp_5_fu_1454_p39;
wire  signed [4:0] tmp_5_fu_1454_p41;
wire   [4:0] tmp_s_fu_1643_p1;
wire   [4:0] tmp_s_fu_1643_p3;
wire   [4:0] tmp_s_fu_1643_p5;
wire   [4:0] tmp_s_fu_1643_p7;
wire   [4:0] tmp_s_fu_1643_p9;
wire   [4:0] tmp_s_fu_1643_p11;
wire   [4:0] tmp_s_fu_1643_p13;
wire   [4:0] tmp_s_fu_1643_p15;
wire   [4:0] tmp_s_fu_1643_p17;
wire   [4:0] tmp_s_fu_1643_p19;
wire   [4:0] tmp_s_fu_1643_p21;
wire   [4:0] tmp_s_fu_1643_p23;
wire   [4:0] tmp_s_fu_1643_p25;
wire   [4:0] tmp_s_fu_1643_p27;
wire   [4:0] tmp_s_fu_1643_p29;
wire   [4:0] tmp_s_fu_1643_p31;
wire  signed [4:0] tmp_s_fu_1643_p33;
wire  signed [4:0] tmp_s_fu_1643_p35;
wire  signed [4:0] tmp_s_fu_1643_p37;
wire  signed [4:0] tmp_s_fu_1643_p39;
wire  signed [4:0] tmp_s_fu_1643_p41;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 acc_im_1_fu_260 = 32'd0;
#0 acc_re_1_fu_264 = 32'd0;
#0 j_1_fu_268 = 6'd0;
#0 ap_done_reg = 1'b0;
end

mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U187(
    .din0(acc_re_1_fu_264),
    .din1(sub_reg_2102),
    .dout(acc_re_2_fu_1096_p2)
);

mvdr_weights_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U188(
    .din0(acc_im_1_fu_260),
    .din1(add_reg_2108),
    .dout(acc_im_2_fu_1100_p2)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_41_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h5 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h6 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h7 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h8 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h9 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'hA ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hB ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hC ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hD ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hE ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hF ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'h10 ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h11 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h12 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h13 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h14 ),
    .din19_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_41_5_32_1_1_U193(
    .din0(x_r_1_load),
    .din1(x_r_2_load),
    .din2(x_r_3_load),
    .din3(x_r_4_load),
    .din4(x_r_5_load),
    .din5(x_r_6_load),
    .din6(x_r_7_load),
    .din7(x_r_8_load),
    .din8(x_r_9_load),
    .din9(x_r_10_load),
    .din10(x_r_11_load),
    .din11(x_r_12_load),
    .din12(x_r_13_load),
    .din13(x_r_14_load),
    .din14(x_r_15_load),
    .din15(x_r_16_load),
    .din16(x_r_17_load),
    .din17(x_r_18_load),
    .din18(x_r_19_load),
    .din19(x_r_20_load),
    .def(tmp_4_fu_1183_p41),
    .sel(trunc_ln204_fu_1179_p1),
    .dout(tmp_4_fu_1183_p43)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_41_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h5 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h6 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h7 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h8 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h9 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'hA ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hB ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hC ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hD ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hE ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hF ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'h10 ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h11 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h12 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h13 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h14 ),
    .din19_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_41_5_32_1_1_U194(
    .din0(x_i_1_load),
    .din1(x_i_2_load),
    .din2(x_i_3_load),
    .din3(x_i_4_load),
    .din4(x_i_5_load),
    .din5(x_i_6_load),
    .din6(x_i_7_load),
    .din7(x_i_8_load),
    .din8(x_i_9_load),
    .din9(x_i_10_load),
    .din10(x_i_11_load),
    .din11(x_i_12_load),
    .din12(x_i_13_load),
    .din13(x_i_14_load),
    .din14(x_i_15_load),
    .din15(x_i_16_load),
    .din16(x_i_17_load),
    .din17(x_i_18_load),
    .din18(x_i_19_load),
    .din19(x_i_20_load),
    .def(tmp_10_fu_1355_p41),
    .sel(trunc_ln204_fu_1179_p1),
    .dout(tmp_10_fu_1355_p43)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U195(
    .din0(A_i_q0),
    .din1(A_i_1_q0),
    .din2(A_i_2_q0),
    .din3(A_i_3_q0),
    .din4(A_i_4_q0),
    .din5(A_i_5_q0),
    .din6(A_i_6_q0),
    .din7(A_i_7_q0),
    .din8(A_i_8_q0),
    .din9(A_i_9_q0),
    .din10(A_i_10_q0),
    .din11(A_i_11_q0),
    .din12(A_i_12_q0),
    .din13(A_i_13_q0),
    .din14(A_i_14_q0),
    .din15(A_i_15_q0),
    .din16(A_i_16_q0),
    .din17(A_i_17_q0),
    .din18(A_i_18_q0),
    .din19(A_i_19_q0),
    .din20(A_i_20_q0),
    .def(tmp_5_fu_1454_p43),
    .sel(empty),
    .dout(tmp_5_fu_1454_p45)
);

(* dissolve_hierarchy = "yes" *) mvdr_weights_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U196(
    .din0(A_r_q0),
    .din1(A_r_1_q0),
    .din2(A_r_2_q0),
    .din3(A_r_3_q0),
    .din4(A_r_4_q0),
    .din5(A_r_5_q0),
    .din6(A_r_6_q0),
    .din7(A_r_7_q0),
    .din8(A_r_8_q0),
    .din9(A_r_9_q0),
    .din10(A_r_10_q0),
    .din11(A_r_11_q0),
    .din12(A_r_12_q0),
    .din13(A_r_13_q0),
    .din14(A_r_14_q0),
    .din15(A_r_15_q0),
    .din16(A_r_16_q0),
    .din17(A_r_17_q0),
    .din18(A_r_18_q0),
    .din19(A_r_19_q0),
    .din20(A_r_20_q0),
    .def(tmp_s_fu_1643_p43),
    .sel(empty),
    .dout(tmp_s_fu_1643_p45)
);

mvdr_weights_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_im_1_fu_260 <= acc_im;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_im_1_fu_260 <= acc_im_2_fu_1100_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_re_1_fu_264 <= acc_re;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_re_1_fu_264 <= acc_re_2_fu_1096_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln204_fu_1148_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_1_fu_268 <= add_ln204_fu_1443_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_268 <= zext_ln198_1_cast_fu_1126_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_reg_2108 <= grp_fu_2069_p_dout0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln204_reg_1823_pp0_iter2_reg <= icmp_ln204_reg_1823_pp0_iter1_reg;
        icmp_ln204_reg_1823_pp0_iter3_reg <= icmp_ln204_reg_1823_pp0_iter2_reg;
        icmp_ln204_reg_1823_pp0_iter4_reg <= icmp_ln204_reg_1823_pp0_iter3_reg;
        mul3_reg_2084 <= grp_fu_7042_p_dout0;
        mul5_reg_2090 <= grp_fu_7046_p_dout0;
        sub_reg_2102 <= grp_fu_2077_p_dout0;
        tmp_10_reg_1965_pp0_iter2_reg <= tmp_10_reg_1965_pp0_iter1_reg;
        tmp_4_reg_1852_pp0_iter2_reg <= tmp_4_reg_1852_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_predicate_pred603_state3 <= (tmp_reg_1817 == 5'd0);
        ap_predicate_pred607_state3 <= (tmp_reg_1817 == 5'd1);
        ap_predicate_pred611_state3 <= (tmp_reg_1817 == 5'd2);
        ap_predicate_pred615_state3 <= (tmp_reg_1817 == 5'd3);
        ap_predicate_pred619_state3 <= (tmp_reg_1817 == 5'd4);
        ap_predicate_pred623_state3 <= (tmp_reg_1817 == 5'd5);
        ap_predicate_pred627_state3 <= (tmp_reg_1817 == 5'd6);
        ap_predicate_pred631_state3 <= (tmp_reg_1817 == 5'd7);
        ap_predicate_pred635_state3 <= (tmp_reg_1817 == 5'd8);
        ap_predicate_pred639_state3 <= (tmp_reg_1817 == 5'd9);
        ap_predicate_pred643_state3 <= (tmp_reg_1817 == 5'd10);
        ap_predicate_pred647_state3 <= (tmp_reg_1817 == 5'd11);
        ap_predicate_pred651_state3 <= (tmp_reg_1817 == 5'd12);
        ap_predicate_pred655_state3 <= (tmp_reg_1817 == 5'd13);
        ap_predicate_pred659_state3 <= (tmp_reg_1817 == 5'd14);
        ap_predicate_pred663_state3 <= (tmp_reg_1817 == 5'd15);
        ap_predicate_pred667_state3 <= (tmp_reg_1817 == 5'd16);
        ap_predicate_pred671_state3 <= (tmp_reg_1817 == 5'd17);
        ap_predicate_pred675_state3 <= (tmp_reg_1817 == 5'd18);
        ap_predicate_pred679_state3 <= (tmp_reg_1817 == 5'd19);
        ap_predicate_pred683_state3 <= (tmp_reg_1817 == 5'd20);
        icmp_ln204_reg_1823 <= icmp_ln204_fu_1148_p2;
        icmp_ln204_reg_1823_pp0_iter1_reg <= icmp_ln204_reg_1823;
        tmp_10_reg_1965 <= tmp_10_fu_1355_p43;
        tmp_10_reg_1965_pp0_iter1_reg <= tmp_10_reg_1965;
        tmp_4_reg_1852 <= tmp_4_fu_1183_p43;
        tmp_4_reg_1852_pp0_iter1_reg <= tmp_4_reg_1852;
        zext_ln204_reg_1827[5 : 0] <= zext_ln204_fu_1154_p1[5 : 0];
        zext_ln204_reg_1827_pp0_iter1_reg[5 : 0] <= zext_ln204_reg_1827[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1104_p0_keep <= tmp_5_fu_1454_p45;
        grp_fu_1104_p1_keep <= tmp_10_reg_1965;
        grp_fu_1108_p0_keep <= tmp_5_fu_1454_p45;
        grp_fu_1108_p1_keep <= tmp_4_reg_1852;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_10_ce0_local = 1'b1;
    end else begin
        A_i_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_11_ce0_local = 1'b1;
    end else begin
        A_i_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_12_ce0_local = 1'b1;
    end else begin
        A_i_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_13_ce0_local = 1'b1;
    end else begin
        A_i_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_14_ce0_local = 1'b1;
    end else begin
        A_i_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_15_ce0_local = 1'b1;
    end else begin
        A_i_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_16_ce0_local = 1'b1;
    end else begin
        A_i_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd17) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_17_ce0_local = 1'b1;
    end else begin
        A_i_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd18) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_18_ce0_local = 1'b1;
    end else begin
        A_i_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd19) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_19_ce0_local = 1'b1;
    end else begin
        A_i_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_1_ce0_local = 1'b1;
    end else begin
        A_i_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd20) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_20_ce0_local = 1'b1;
    end else begin
        A_i_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_2_ce0_local = 1'b1;
    end else begin
        A_i_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_3_ce0_local = 1'b1;
    end else begin
        A_i_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_4_ce0_local = 1'b1;
    end else begin
        A_i_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_5_ce0_local = 1'b1;
    end else begin
        A_i_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_6_ce0_local = 1'b1;
    end else begin
        A_i_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_7_ce0_local = 1'b1;
    end else begin
        A_i_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_8_ce0_local = 1'b1;
    end else begin
        A_i_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_9_ce0_local = 1'b1;
    end else begin
        A_i_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_read_fu_512_p2 == 5'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_i_ce0_local = 1'b1;
    end else begin
        A_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred643_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_10_ce0_local = 1'b1;
    end else begin
        A_r_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred647_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_11_ce0_local = 1'b1;
    end else begin
        A_r_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred651_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_12_ce0_local = 1'b1;
    end else begin
        A_r_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred655_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_13_ce0_local = 1'b1;
    end else begin
        A_r_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred659_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_14_ce0_local = 1'b1;
    end else begin
        A_r_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred663_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_15_ce0_local = 1'b1;
    end else begin
        A_r_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred667_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_16_ce0_local = 1'b1;
    end else begin
        A_r_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred671_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_17_ce0_local = 1'b1;
    end else begin
        A_r_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred675_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_18_ce0_local = 1'b1;
    end else begin
        A_r_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred679_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_19_ce0_local = 1'b1;
    end else begin
        A_r_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred607_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_1_ce0_local = 1'b1;
    end else begin
        A_r_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred683_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_20_ce0_local = 1'b1;
    end else begin
        A_r_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred611_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_2_ce0_local = 1'b1;
    end else begin
        A_r_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred615_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_3_ce0_local = 1'b1;
    end else begin
        A_r_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred619_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_4_ce0_local = 1'b1;
    end else begin
        A_r_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred623_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_5_ce0_local = 1'b1;
    end else begin
        A_r_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred627_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_6_ce0_local = 1'b1;
    end else begin
        A_r_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred631_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_7_ce0_local = 1'b1;
    end else begin
        A_r_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred635_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_8_ce0_local = 1'b1;
    end else begin
        A_r_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred639_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_9_ce0_local = 1'b1;
    end else begin
        A_r_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred603_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_r_ce0_local = 1'b1;
    end else begin
        A_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_reg_1823_pp0_iter4_reg == 1'd1))) begin
        acc_im_1_out_ap_vld = 1'b1;
    end else begin
        acc_im_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_reg_1823_pp0_iter4_reg == 1'd1))) begin
        acc_re_1_out_ap_vld = 1'b1;
    end else begin
        acc_re_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_1148_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j = zext_ln198_1_cast_fu_1126_p1;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_268;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1104_p0 = tmp_5_fu_1454_p45;
    end else begin
        grp_fu_1104_p0 = grp_fu_1104_p0_keep;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1104_p1 = tmp_10_reg_1965;
    end else begin
        grp_fu_1104_p1 = grp_fu_1104_p1_keep;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1108_p0 = tmp_5_fu_1454_p45;
    end else begin
        grp_fu_1108_p0 = grp_fu_1108_p0_keep;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1108_p1 = tmp_4_reg_1852;
    end else begin
        grp_fu_1108_p1 = grp_fu_1108_p1_keep;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_i_10_address0 = zext_ln204_fu_1154_p1;

assign A_i_10_ce0 = A_i_10_ce0_local;

assign A_i_11_address0 = zext_ln204_fu_1154_p1;

assign A_i_11_ce0 = A_i_11_ce0_local;

assign A_i_12_address0 = zext_ln204_fu_1154_p1;

assign A_i_12_ce0 = A_i_12_ce0_local;

assign A_i_13_address0 = zext_ln204_fu_1154_p1;

assign A_i_13_ce0 = A_i_13_ce0_local;

assign A_i_14_address0 = zext_ln204_fu_1154_p1;

assign A_i_14_ce0 = A_i_14_ce0_local;

assign A_i_15_address0 = zext_ln204_fu_1154_p1;

assign A_i_15_ce0 = A_i_15_ce0_local;

assign A_i_16_address0 = zext_ln204_fu_1154_p1;

assign A_i_16_ce0 = A_i_16_ce0_local;

assign A_i_17_address0 = zext_ln204_fu_1154_p1;

assign A_i_17_ce0 = A_i_17_ce0_local;

assign A_i_18_address0 = zext_ln204_fu_1154_p1;

assign A_i_18_ce0 = A_i_18_ce0_local;

assign A_i_19_address0 = zext_ln204_fu_1154_p1;

assign A_i_19_ce0 = A_i_19_ce0_local;

assign A_i_1_address0 = zext_ln204_fu_1154_p1;

assign A_i_1_ce0 = A_i_1_ce0_local;

assign A_i_20_address0 = zext_ln204_fu_1154_p1;

assign A_i_20_ce0 = A_i_20_ce0_local;

assign A_i_2_address0 = zext_ln204_fu_1154_p1;

assign A_i_2_ce0 = A_i_2_ce0_local;

assign A_i_3_address0 = zext_ln204_fu_1154_p1;

assign A_i_3_ce0 = A_i_3_ce0_local;

assign A_i_4_address0 = zext_ln204_fu_1154_p1;

assign A_i_4_ce0 = A_i_4_ce0_local;

assign A_i_5_address0 = zext_ln204_fu_1154_p1;

assign A_i_5_ce0 = A_i_5_ce0_local;

assign A_i_6_address0 = zext_ln204_fu_1154_p1;

assign A_i_6_ce0 = A_i_6_ce0_local;

assign A_i_7_address0 = zext_ln204_fu_1154_p1;

assign A_i_7_ce0 = A_i_7_ce0_local;

assign A_i_8_address0 = zext_ln204_fu_1154_p1;

assign A_i_8_ce0 = A_i_8_ce0_local;

assign A_i_9_address0 = zext_ln204_fu_1154_p1;

assign A_i_9_ce0 = A_i_9_ce0_local;

assign A_i_address0 = zext_ln204_fu_1154_p1;

assign A_i_ce0 = A_i_ce0_local;

assign A_r_10_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_10_ce0 = A_r_10_ce0_local;

assign A_r_11_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_11_ce0 = A_r_11_ce0_local;

assign A_r_12_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_12_ce0 = A_r_12_ce0_local;

assign A_r_13_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_13_ce0 = A_r_13_ce0_local;

assign A_r_14_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_14_ce0 = A_r_14_ce0_local;

assign A_r_15_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_15_ce0 = A_r_15_ce0_local;

assign A_r_16_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_16_ce0 = A_r_16_ce0_local;

assign A_r_17_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_17_ce0 = A_r_17_ce0_local;

assign A_r_18_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_18_ce0 = A_r_18_ce0_local;

assign A_r_19_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_19_ce0 = A_r_19_ce0_local;

assign A_r_1_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_1_ce0 = A_r_1_ce0_local;

assign A_r_20_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_20_ce0 = A_r_20_ce0_local;

assign A_r_2_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_2_ce0 = A_r_2_ce0_local;

assign A_r_3_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_3_ce0 = A_r_3_ce0_local;

assign A_r_4_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_4_ce0 = A_r_4_ce0_local;

assign A_r_5_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_5_ce0 = A_r_5_ce0_local;

assign A_r_6_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_6_ce0 = A_r_6_ce0_local;

assign A_r_7_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_7_ce0 = A_r_7_ce0_local;

assign A_r_8_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_8_ce0 = A_r_8_ce0_local;

assign A_r_9_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_9_ce0 = A_r_9_ce0_local;

assign A_r_address0 = zext_ln204_reg_1827_pp0_iter1_reg;

assign A_r_ce0 = A_r_ce0_local;

assign acc_im_1_out = acc_im_1_fu_260;

assign acc_re_1_out = acc_re_1_fu_264;

assign add_ln204_fu_1443_p2 = (ap_sig_allocacmp_j + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_2069_p_ce = 1'b1;

assign grp_fu_2069_p_din0 = 32'd0;

assign grp_fu_2069_p_din1 = tmp_s_fu_1643_p45;

assign grp_fu_2069_p_din2 = tmp_10_reg_1965_pp0_iter2_reg;

assign grp_fu_2069_p_din3 = mul5_reg_2090;

assign grp_fu_2077_p_ce = 1'b1;

assign grp_fu_2077_p_din0 = 32'd0;

assign grp_fu_2077_p_din1 = tmp_s_fu_1643_p45;

assign grp_fu_2077_p_din2 = tmp_4_reg_1852_pp0_iter2_reg;

assign grp_fu_2077_p_din3 = mul3_reg_2084;

assign grp_fu_7042_p_din0 = grp_fu_1104_p0;

assign grp_fu_7042_p_din1 = grp_fu_1104_p1;

assign grp_fu_7046_p_din0 = grp_fu_1108_p0;

assign grp_fu_7046_p_din1 = grp_fu_1108_p1;

assign icmp_ln204_fu_1148_p2 = ((ap_sig_allocacmp_j == 6'd21) ? 1'b1 : 1'b0);

assign tmp_10_fu_1355_p41 = 'bx;

assign tmp_4_fu_1183_p41 = 'bx;

assign tmp_5_fu_1454_p43 = 'bx;

assign tmp_read_fu_512_p2 = empty;

assign tmp_reg_1817 = empty;

assign tmp_s_fu_1643_p43 = 'bx;

assign trunc_ln204_fu_1179_p1 = ap_sig_allocacmp_j[4:0];

assign zext_ln198_1_cast_fu_1126_p1 = zext_ln198_1;

assign zext_ln204_fu_1154_p1 = ap_sig_allocacmp_j;

always @ (posedge ap_clk) begin
    zext_ln204_reg_1827[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_1827_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //mvdr_weights_mvdr_weights_Pipeline_BACK_SUB_INNER
