// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1
#(parameter
  ID = 1,
  NUM_STAGE = 1,
  OUTPUT_DATA_WIDTH = 1,
  DWIDTH  = 32
)(
    input wire clk,
    input reset,
    input ce,
    input wire [DWIDTH-1:0] in_data,
    input in_valid,
    input in_last,
    output wire [DWIDTH-1:0] out_data
);

wire out_last;
wire out_valid;
wire reset_invert = ~reset;

//-------------------Instantiation----------------------------

mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip mvdr_weights_facc_32ns_32ns_1ns_32_2_primitive_dsp_1_ip_u (
    .aclk(clk),
    .aclken(ce),
    .aresetn(reset_invert),
    .s_axis_a_tvalid(in_valid),
    .s_axis_a_tdata(in_data),
    .s_axis_a_tlast(in_last),
    .m_axis_result_tvalid(out_valid),
    .m_axis_result_tdata(out_data),
    .m_axis_result_tlast(out_last)
);

//-------------------End Instantiation------------------------
endmodule
