// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module covariance_estimation_covariance_estimation_Pipeline_LOAD_SNAPSHOT_LOAD_CHANNEL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_in_TVALID,
        X_buf_re_address0,
        X_buf_re_ce0,
        X_buf_re_we0,
        X_buf_re_d0,
        X_buf_re_1_address0,
        X_buf_re_1_ce0,
        X_buf_re_1_we0,
        X_buf_re_1_d0,
        X_buf_re_2_address0,
        X_buf_re_2_ce0,
        X_buf_re_2_we0,
        X_buf_re_2_d0,
        X_buf_re_3_address0,
        X_buf_re_3_ce0,
        X_buf_re_3_we0,
        X_buf_re_3_d0,
        X_buf_re_4_address0,
        X_buf_re_4_ce0,
        X_buf_re_4_we0,
        X_buf_re_4_d0,
        X_buf_re_5_address0,
        X_buf_re_5_ce0,
        X_buf_re_5_we0,
        X_buf_re_5_d0,
        X_buf_re_6_address0,
        X_buf_re_6_ce0,
        X_buf_re_6_we0,
        X_buf_re_6_d0,
        X_buf_re_7_address0,
        X_buf_re_7_ce0,
        X_buf_re_7_we0,
        X_buf_re_7_d0,
        X_buf_re_8_address0,
        X_buf_re_8_ce0,
        X_buf_re_8_we0,
        X_buf_re_8_d0,
        X_buf_re_9_address0,
        X_buf_re_9_ce0,
        X_buf_re_9_we0,
        X_buf_re_9_d0,
        X_buf_re_10_address0,
        X_buf_re_10_ce0,
        X_buf_re_10_we0,
        X_buf_re_10_d0,
        X_buf_re_11_address0,
        X_buf_re_11_ce0,
        X_buf_re_11_we0,
        X_buf_re_11_d0,
        X_buf_re_12_address0,
        X_buf_re_12_ce0,
        X_buf_re_12_we0,
        X_buf_re_12_d0,
        X_buf_re_13_address0,
        X_buf_re_13_ce0,
        X_buf_re_13_we0,
        X_buf_re_13_d0,
        X_buf_re_14_address0,
        X_buf_re_14_ce0,
        X_buf_re_14_we0,
        X_buf_re_14_d0,
        X_buf_re_15_address0,
        X_buf_re_15_ce0,
        X_buf_re_15_we0,
        X_buf_re_15_d0,
        X_buf_re_16_address0,
        X_buf_re_16_ce0,
        X_buf_re_16_we0,
        X_buf_re_16_d0,
        X_buf_re_17_address0,
        X_buf_re_17_ce0,
        X_buf_re_17_we0,
        X_buf_re_17_d0,
        X_buf_re_18_address0,
        X_buf_re_18_ce0,
        X_buf_re_18_we0,
        X_buf_re_18_d0,
        X_buf_re_19_address0,
        X_buf_re_19_ce0,
        X_buf_re_19_we0,
        X_buf_re_19_d0,
        X_buf_re_20_address0,
        X_buf_re_20_ce0,
        X_buf_re_20_we0,
        X_buf_re_20_d0,
        X_buf_im_address0,
        X_buf_im_ce0,
        X_buf_im_we0,
        X_buf_im_d0,
        X_buf_im_1_address0,
        X_buf_im_1_ce0,
        X_buf_im_1_we0,
        X_buf_im_1_d0,
        X_buf_im_2_address0,
        X_buf_im_2_ce0,
        X_buf_im_2_we0,
        X_buf_im_2_d0,
        X_buf_im_3_address0,
        X_buf_im_3_ce0,
        X_buf_im_3_we0,
        X_buf_im_3_d0,
        X_buf_im_4_address0,
        X_buf_im_4_ce0,
        X_buf_im_4_we0,
        X_buf_im_4_d0,
        X_buf_im_5_address0,
        X_buf_im_5_ce0,
        X_buf_im_5_we0,
        X_buf_im_5_d0,
        X_buf_im_6_address0,
        X_buf_im_6_ce0,
        X_buf_im_6_we0,
        X_buf_im_6_d0,
        X_buf_im_7_address0,
        X_buf_im_7_ce0,
        X_buf_im_7_we0,
        X_buf_im_7_d0,
        X_buf_im_8_address0,
        X_buf_im_8_ce0,
        X_buf_im_8_we0,
        X_buf_im_8_d0,
        X_buf_im_9_address0,
        X_buf_im_9_ce0,
        X_buf_im_9_we0,
        X_buf_im_9_d0,
        X_buf_im_10_address0,
        X_buf_im_10_ce0,
        X_buf_im_10_we0,
        X_buf_im_10_d0,
        X_buf_im_11_address0,
        X_buf_im_11_ce0,
        X_buf_im_11_we0,
        X_buf_im_11_d0,
        X_buf_im_12_address0,
        X_buf_im_12_ce0,
        X_buf_im_12_we0,
        X_buf_im_12_d0,
        X_buf_im_13_address0,
        X_buf_im_13_ce0,
        X_buf_im_13_we0,
        X_buf_im_13_d0,
        X_buf_im_14_address0,
        X_buf_im_14_ce0,
        X_buf_im_14_we0,
        X_buf_im_14_d0,
        X_buf_im_15_address0,
        X_buf_im_15_ce0,
        X_buf_im_15_we0,
        X_buf_im_15_d0,
        X_buf_im_16_address0,
        X_buf_im_16_ce0,
        X_buf_im_16_we0,
        X_buf_im_16_d0,
        X_buf_im_17_address0,
        X_buf_im_17_ce0,
        X_buf_im_17_we0,
        X_buf_im_17_d0,
        X_buf_im_18_address0,
        X_buf_im_18_ce0,
        X_buf_im_18_we0,
        X_buf_im_18_d0,
        X_buf_im_19_address0,
        X_buf_im_19_ce0,
        X_buf_im_19_we0,
        X_buf_im_19_d0,
        X_buf_im_20_address0,
        X_buf_im_20_ce0,
        X_buf_im_20_we0,
        X_buf_im_20_d0,
        y_in_TDATA,
        y_in_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   y_in_TVALID;
output  [9:0] X_buf_re_address0;
output   X_buf_re_ce0;
output   X_buf_re_we0;
output  [15:0] X_buf_re_d0;
output  [9:0] X_buf_re_1_address0;
output   X_buf_re_1_ce0;
output   X_buf_re_1_we0;
output  [15:0] X_buf_re_1_d0;
output  [9:0] X_buf_re_2_address0;
output   X_buf_re_2_ce0;
output   X_buf_re_2_we0;
output  [15:0] X_buf_re_2_d0;
output  [9:0] X_buf_re_3_address0;
output   X_buf_re_3_ce0;
output   X_buf_re_3_we0;
output  [15:0] X_buf_re_3_d0;
output  [9:0] X_buf_re_4_address0;
output   X_buf_re_4_ce0;
output   X_buf_re_4_we0;
output  [15:0] X_buf_re_4_d0;
output  [9:0] X_buf_re_5_address0;
output   X_buf_re_5_ce0;
output   X_buf_re_5_we0;
output  [15:0] X_buf_re_5_d0;
output  [9:0] X_buf_re_6_address0;
output   X_buf_re_6_ce0;
output   X_buf_re_6_we0;
output  [15:0] X_buf_re_6_d0;
output  [9:0] X_buf_re_7_address0;
output   X_buf_re_7_ce0;
output   X_buf_re_7_we0;
output  [15:0] X_buf_re_7_d0;
output  [9:0] X_buf_re_8_address0;
output   X_buf_re_8_ce0;
output   X_buf_re_8_we0;
output  [15:0] X_buf_re_8_d0;
output  [9:0] X_buf_re_9_address0;
output   X_buf_re_9_ce0;
output   X_buf_re_9_we0;
output  [15:0] X_buf_re_9_d0;
output  [9:0] X_buf_re_10_address0;
output   X_buf_re_10_ce0;
output   X_buf_re_10_we0;
output  [15:0] X_buf_re_10_d0;
output  [9:0] X_buf_re_11_address0;
output   X_buf_re_11_ce0;
output   X_buf_re_11_we0;
output  [15:0] X_buf_re_11_d0;
output  [9:0] X_buf_re_12_address0;
output   X_buf_re_12_ce0;
output   X_buf_re_12_we0;
output  [15:0] X_buf_re_12_d0;
output  [9:0] X_buf_re_13_address0;
output   X_buf_re_13_ce0;
output   X_buf_re_13_we0;
output  [15:0] X_buf_re_13_d0;
output  [9:0] X_buf_re_14_address0;
output   X_buf_re_14_ce0;
output   X_buf_re_14_we0;
output  [15:0] X_buf_re_14_d0;
output  [9:0] X_buf_re_15_address0;
output   X_buf_re_15_ce0;
output   X_buf_re_15_we0;
output  [15:0] X_buf_re_15_d0;
output  [9:0] X_buf_re_16_address0;
output   X_buf_re_16_ce0;
output   X_buf_re_16_we0;
output  [15:0] X_buf_re_16_d0;
output  [9:0] X_buf_re_17_address0;
output   X_buf_re_17_ce0;
output   X_buf_re_17_we0;
output  [15:0] X_buf_re_17_d0;
output  [9:0] X_buf_re_18_address0;
output   X_buf_re_18_ce0;
output   X_buf_re_18_we0;
output  [15:0] X_buf_re_18_d0;
output  [9:0] X_buf_re_19_address0;
output   X_buf_re_19_ce0;
output   X_buf_re_19_we0;
output  [15:0] X_buf_re_19_d0;
output  [9:0] X_buf_re_20_address0;
output   X_buf_re_20_ce0;
output   X_buf_re_20_we0;
output  [15:0] X_buf_re_20_d0;
output  [9:0] X_buf_im_address0;
output   X_buf_im_ce0;
output   X_buf_im_we0;
output  [15:0] X_buf_im_d0;
output  [9:0] X_buf_im_1_address0;
output   X_buf_im_1_ce0;
output   X_buf_im_1_we0;
output  [15:0] X_buf_im_1_d0;
output  [9:0] X_buf_im_2_address0;
output   X_buf_im_2_ce0;
output   X_buf_im_2_we0;
output  [15:0] X_buf_im_2_d0;
output  [9:0] X_buf_im_3_address0;
output   X_buf_im_3_ce0;
output   X_buf_im_3_we0;
output  [15:0] X_buf_im_3_d0;
output  [9:0] X_buf_im_4_address0;
output   X_buf_im_4_ce0;
output   X_buf_im_4_we0;
output  [15:0] X_buf_im_4_d0;
output  [9:0] X_buf_im_5_address0;
output   X_buf_im_5_ce0;
output   X_buf_im_5_we0;
output  [15:0] X_buf_im_5_d0;
output  [9:0] X_buf_im_6_address0;
output   X_buf_im_6_ce0;
output   X_buf_im_6_we0;
output  [15:0] X_buf_im_6_d0;
output  [9:0] X_buf_im_7_address0;
output   X_buf_im_7_ce0;
output   X_buf_im_7_we0;
output  [15:0] X_buf_im_7_d0;
output  [9:0] X_buf_im_8_address0;
output   X_buf_im_8_ce0;
output   X_buf_im_8_we0;
output  [15:0] X_buf_im_8_d0;
output  [9:0] X_buf_im_9_address0;
output   X_buf_im_9_ce0;
output   X_buf_im_9_we0;
output  [15:0] X_buf_im_9_d0;
output  [9:0] X_buf_im_10_address0;
output   X_buf_im_10_ce0;
output   X_buf_im_10_we0;
output  [15:0] X_buf_im_10_d0;
output  [9:0] X_buf_im_11_address0;
output   X_buf_im_11_ce0;
output   X_buf_im_11_we0;
output  [15:0] X_buf_im_11_d0;
output  [9:0] X_buf_im_12_address0;
output   X_buf_im_12_ce0;
output   X_buf_im_12_we0;
output  [15:0] X_buf_im_12_d0;
output  [9:0] X_buf_im_13_address0;
output   X_buf_im_13_ce0;
output   X_buf_im_13_we0;
output  [15:0] X_buf_im_13_d0;
output  [9:0] X_buf_im_14_address0;
output   X_buf_im_14_ce0;
output   X_buf_im_14_we0;
output  [15:0] X_buf_im_14_d0;
output  [9:0] X_buf_im_15_address0;
output   X_buf_im_15_ce0;
output   X_buf_im_15_we0;
output  [15:0] X_buf_im_15_d0;
output  [9:0] X_buf_im_16_address0;
output   X_buf_im_16_ce0;
output   X_buf_im_16_we0;
output  [15:0] X_buf_im_16_d0;
output  [9:0] X_buf_im_17_address0;
output   X_buf_im_17_ce0;
output   X_buf_im_17_we0;
output  [15:0] X_buf_im_17_d0;
output  [9:0] X_buf_im_18_address0;
output   X_buf_im_18_ce0;
output   X_buf_im_18_we0;
output  [15:0] X_buf_im_18_d0;
output  [9:0] X_buf_im_19_address0;
output   X_buf_im_19_ce0;
output   X_buf_im_19_we0;
output  [15:0] X_buf_im_19_d0;
output  [9:0] X_buf_im_20_address0;
output   X_buf_im_20_ce0;
output   X_buf_im_20_we0;
output  [15:0] X_buf_im_20_d0;
input  [63:0] y_in_TDATA;
output   y_in_TREADY;

reg ap_idle;
reg y_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln52_fu_766_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    y_in_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [63:0] zext_ln52_fu_811_p1;
reg   [4:0] ch_fu_172;
wire   [4:0] add_ln54_fu_1127_p2;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_loop_init;
reg   [9:0] t_fu_176;
wire   [9:0] select_ln52_1_fu_803_p3;
reg   [14:0] indvar_flatten_fu_180;
wire   [14:0] add_ln52_fu_760_p2;
reg    ap_block_pp0_stage0_11001;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    X_buf_re_19_we0_local;
wire   [4:0] select_ln52_fu_789_p3;
reg    X_buf_re_19_ce0_local;
reg    X_buf_im_19_we0_local;
wire   [15:0] xi_fu_889_p1;
reg    X_buf_im_19_ce0_local;
reg    X_buf_re_18_we0_local;
reg    X_buf_re_18_ce0_local;
reg    X_buf_im_18_we0_local;
reg    X_buf_im_18_ce0_local;
reg    X_buf_re_17_we0_local;
reg    X_buf_re_17_ce0_local;
reg    X_buf_im_17_we0_local;
reg    X_buf_im_17_ce0_local;
reg    X_buf_re_16_we0_local;
reg    X_buf_re_16_ce0_local;
reg    X_buf_im_16_we0_local;
reg    X_buf_im_16_ce0_local;
reg    X_buf_re_15_we0_local;
reg    X_buf_re_15_ce0_local;
reg    X_buf_im_15_we0_local;
reg    X_buf_im_15_ce0_local;
reg    X_buf_re_14_we0_local;
reg    X_buf_re_14_ce0_local;
reg    X_buf_im_14_we0_local;
reg    X_buf_im_14_ce0_local;
reg    X_buf_re_13_we0_local;
reg    X_buf_re_13_ce0_local;
reg    X_buf_im_13_we0_local;
reg    X_buf_im_13_ce0_local;
reg    X_buf_re_12_we0_local;
reg    X_buf_re_12_ce0_local;
reg    X_buf_im_12_we0_local;
reg    X_buf_im_12_ce0_local;
reg    X_buf_re_11_we0_local;
reg    X_buf_re_11_ce0_local;
reg    X_buf_im_11_we0_local;
reg    X_buf_im_11_ce0_local;
reg    X_buf_re_10_we0_local;
reg    X_buf_re_10_ce0_local;
reg    X_buf_im_10_we0_local;
reg    X_buf_im_10_ce0_local;
reg    X_buf_re_9_we0_local;
reg    X_buf_re_9_ce0_local;
reg    X_buf_im_9_we0_local;
reg    X_buf_im_9_ce0_local;
reg    X_buf_re_8_we0_local;
reg    X_buf_re_8_ce0_local;
reg    X_buf_im_8_we0_local;
reg    X_buf_im_8_ce0_local;
reg    X_buf_re_7_we0_local;
reg    X_buf_re_7_ce0_local;
reg    X_buf_im_7_we0_local;
reg    X_buf_im_7_ce0_local;
reg    X_buf_re_6_we0_local;
reg    X_buf_re_6_ce0_local;
reg    X_buf_im_6_we0_local;
reg    X_buf_im_6_ce0_local;
reg    X_buf_re_5_we0_local;
reg    X_buf_re_5_ce0_local;
reg    X_buf_im_5_we0_local;
reg    X_buf_im_5_ce0_local;
reg    X_buf_re_4_we0_local;
reg    X_buf_re_4_ce0_local;
reg    X_buf_im_4_we0_local;
reg    X_buf_im_4_ce0_local;
reg    X_buf_re_3_we0_local;
reg    X_buf_re_3_ce0_local;
reg    X_buf_im_3_we0_local;
reg    X_buf_im_3_ce0_local;
reg    X_buf_re_2_we0_local;
reg    X_buf_re_2_ce0_local;
reg    X_buf_im_2_we0_local;
reg    X_buf_im_2_ce0_local;
reg    X_buf_re_1_we0_local;
reg    X_buf_re_1_ce0_local;
reg    X_buf_im_1_we0_local;
reg    X_buf_im_1_ce0_local;
reg    X_buf_re_we0_local;
reg    X_buf_re_ce0_local;
reg    X_buf_im_we0_local;
reg    X_buf_im_ce0_local;
reg    X_buf_re_20_we0_local;
reg    X_buf_re_20_ce0_local;
reg    X_buf_im_20_we0_local;
reg    X_buf_im_20_ce0_local;
wire   [0:0] icmp_ln54_fu_783_p2;
wire   [9:0] add_ln52_1_fu_797_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ch_fu_172 = 5'd0;
#0 t_fu_176 = 10'd0;
#0 indvar_flatten_fu_180 = 15'd0;
#0 ap_done_reg = 1'b0;
end

covariance_estimation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ch_fu_172 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ch_fu_172 <= add_ln54_fu_1127_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_766_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_180 <= add_ln52_fu_760_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_180 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_fu_176 <= 10'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            t_fu_176 <= select_ln52_1_fu_803_p3;
        end
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_10_ce0_local = 1'b1;
    end else begin
        X_buf_im_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_10_we0_local = 1'b1;
    end else begin
        X_buf_im_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_11_ce0_local = 1'b1;
    end else begin
        X_buf_im_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_11_we0_local = 1'b1;
    end else begin
        X_buf_im_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_12_ce0_local = 1'b1;
    end else begin
        X_buf_im_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_12_we0_local = 1'b1;
    end else begin
        X_buf_im_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_13_ce0_local = 1'b1;
    end else begin
        X_buf_im_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_13_we0_local = 1'b1;
    end else begin
        X_buf_im_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_14_ce0_local = 1'b1;
    end else begin
        X_buf_im_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_14_we0_local = 1'b1;
    end else begin
        X_buf_im_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_15_ce0_local = 1'b1;
    end else begin
        X_buf_im_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_15_we0_local = 1'b1;
    end else begin
        X_buf_im_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_16_ce0_local = 1'b1;
    end else begin
        X_buf_im_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_16_we0_local = 1'b1;
    end else begin
        X_buf_im_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_17_ce0_local = 1'b1;
    end else begin
        X_buf_im_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_17_we0_local = 1'b1;
    end else begin
        X_buf_im_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_18_ce0_local = 1'b1;
    end else begin
        X_buf_im_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_18_we0_local = 1'b1;
    end else begin
        X_buf_im_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_19_ce0_local = 1'b1;
    end else begin
        X_buf_im_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_19_we0_local = 1'b1;
    end else begin
        X_buf_im_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_1_ce0_local = 1'b1;
    end else begin
        X_buf_im_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_1_we0_local = 1'b1;
    end else begin
        X_buf_im_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln52_fu_789_p3 == 5'd0) & ~(select_ln52_fu_789_p3 == 5'd1) & ~(select_ln52_fu_789_p3 == 5'd2) & ~(select_ln52_fu_789_p3 == 5'd3) & ~(select_ln52_fu_789_p3 == 5'd4) & ~(select_ln52_fu_789_p3 == 5'd5) & ~(select_ln52_fu_789_p3 == 5'd6) & ~(select_ln52_fu_789_p3 == 5'd7) & ~(select_ln52_fu_789_p3 == 5'd8) & ~(select_ln52_fu_789_p3 == 5'd9) & ~(select_ln52_fu_789_p3 == 5'd10) & ~(select_ln52_fu_789_p3 == 5'd11) & ~(select_ln52_fu_789_p3 == 5'd12) & ~(select_ln52_fu_789_p3 == 5'd13) & ~(select_ln52_fu_789_p3 == 5'd14) & ~(select_ln52_fu_789_p3 == 5'd15) & ~(select_ln52_fu_789_p3 == 5'd16) & ~(select_ln52_fu_789_p3 == 5'd17) & ~(select_ln52_fu_789_p3 == 5'd18) & ~(select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_20_ce0_local = 1'b1;
    end else begin
        X_buf_im_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln52_fu_789_p3 == 5'd0) & ~(select_ln52_fu_789_p3 == 5'd1) & ~(select_ln52_fu_789_p3 == 5'd2) & ~(select_ln52_fu_789_p3 == 5'd3) & ~(select_ln52_fu_789_p3 == 5'd4) & ~(select_ln52_fu_789_p3 == 5'd5) & ~(select_ln52_fu_789_p3 == 5'd6) & ~(select_ln52_fu_789_p3 == 5'd7) & ~(select_ln52_fu_789_p3 == 5'd8) & ~(select_ln52_fu_789_p3 == 5'd9) & ~(select_ln52_fu_789_p3 == 5'd10) & ~(select_ln52_fu_789_p3 == 5'd11) & ~(select_ln52_fu_789_p3 == 5'd12) & ~(select_ln52_fu_789_p3 == 5'd13) & ~(select_ln52_fu_789_p3 == 5'd14) & ~(select_ln52_fu_789_p3 == 5'd15) & ~(select_ln52_fu_789_p3 == 5'd16) & ~(select_ln52_fu_789_p3 == 5'd17) & ~(select_ln52_fu_789_p3 == 5'd18) & ~(select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_20_we0_local = 1'b1;
    end else begin
        X_buf_im_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_2_ce0_local = 1'b1;
    end else begin
        X_buf_im_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_2_we0_local = 1'b1;
    end else begin
        X_buf_im_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_3_ce0_local = 1'b1;
    end else begin
        X_buf_im_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_3_we0_local = 1'b1;
    end else begin
        X_buf_im_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_4_ce0_local = 1'b1;
    end else begin
        X_buf_im_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_4_we0_local = 1'b1;
    end else begin
        X_buf_im_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_5_ce0_local = 1'b1;
    end else begin
        X_buf_im_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_5_we0_local = 1'b1;
    end else begin
        X_buf_im_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_6_ce0_local = 1'b1;
    end else begin
        X_buf_im_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_6_we0_local = 1'b1;
    end else begin
        X_buf_im_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_7_ce0_local = 1'b1;
    end else begin
        X_buf_im_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_7_we0_local = 1'b1;
    end else begin
        X_buf_im_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_8_ce0_local = 1'b1;
    end else begin
        X_buf_im_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_8_we0_local = 1'b1;
    end else begin
        X_buf_im_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_9_ce0_local = 1'b1;
    end else begin
        X_buf_im_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_9_we0_local = 1'b1;
    end else begin
        X_buf_im_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_ce0_local = 1'b1;
    end else begin
        X_buf_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_we0_local = 1'b1;
    end else begin
        X_buf_im_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_10_ce0_local = 1'b1;
    end else begin
        X_buf_re_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_10_we0_local = 1'b1;
    end else begin
        X_buf_re_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_11_ce0_local = 1'b1;
    end else begin
        X_buf_re_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_11_we0_local = 1'b1;
    end else begin
        X_buf_re_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_12_ce0_local = 1'b1;
    end else begin
        X_buf_re_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_12_we0_local = 1'b1;
    end else begin
        X_buf_re_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_13_ce0_local = 1'b1;
    end else begin
        X_buf_re_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_13_we0_local = 1'b1;
    end else begin
        X_buf_re_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_14_ce0_local = 1'b1;
    end else begin
        X_buf_re_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_14_we0_local = 1'b1;
    end else begin
        X_buf_re_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_15_ce0_local = 1'b1;
    end else begin
        X_buf_re_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_15_we0_local = 1'b1;
    end else begin
        X_buf_re_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_16_ce0_local = 1'b1;
    end else begin
        X_buf_re_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_16_we0_local = 1'b1;
    end else begin
        X_buf_re_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_17_ce0_local = 1'b1;
    end else begin
        X_buf_re_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_17_we0_local = 1'b1;
    end else begin
        X_buf_re_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_18_ce0_local = 1'b1;
    end else begin
        X_buf_re_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_18_we0_local = 1'b1;
    end else begin
        X_buf_re_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_19_ce0_local = 1'b1;
    end else begin
        X_buf_re_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_19_we0_local = 1'b1;
    end else begin
        X_buf_re_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_1_ce0_local = 1'b1;
    end else begin
        X_buf_re_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_1_we0_local = 1'b1;
    end else begin
        X_buf_re_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln52_fu_789_p3 == 5'd0) & ~(select_ln52_fu_789_p3 == 5'd1) & ~(select_ln52_fu_789_p3 == 5'd2) & ~(select_ln52_fu_789_p3 == 5'd3) & ~(select_ln52_fu_789_p3 == 5'd4) & ~(select_ln52_fu_789_p3 == 5'd5) & ~(select_ln52_fu_789_p3 == 5'd6) & ~(select_ln52_fu_789_p3 == 5'd7) & ~(select_ln52_fu_789_p3 == 5'd8) & ~(select_ln52_fu_789_p3 == 5'd9) & ~(select_ln52_fu_789_p3 == 5'd10) & ~(select_ln52_fu_789_p3 == 5'd11) & ~(select_ln52_fu_789_p3 == 5'd12) & ~(select_ln52_fu_789_p3 == 5'd13) & ~(select_ln52_fu_789_p3 == 5'd14) & ~(select_ln52_fu_789_p3 == 5'd15) & ~(select_ln52_fu_789_p3 == 5'd16) & ~(select_ln52_fu_789_p3 == 5'd17) & ~(select_ln52_fu_789_p3 == 5'd18) & ~(select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_20_ce0_local = 1'b1;
    end else begin
        X_buf_re_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln52_fu_789_p3 == 5'd0) & ~(select_ln52_fu_789_p3 == 5'd1) & ~(select_ln52_fu_789_p3 == 5'd2) & ~(select_ln52_fu_789_p3 == 5'd3) & ~(select_ln52_fu_789_p3 == 5'd4) & ~(select_ln52_fu_789_p3 == 5'd5) & ~(select_ln52_fu_789_p3 == 5'd6) & ~(select_ln52_fu_789_p3 == 5'd7) & ~(select_ln52_fu_789_p3 == 5'd8) & ~(select_ln52_fu_789_p3 == 5'd9) & ~(select_ln52_fu_789_p3 == 5'd10) & ~(select_ln52_fu_789_p3 == 5'd11) & ~(select_ln52_fu_789_p3 == 5'd12) & ~(select_ln52_fu_789_p3 == 5'd13) & ~(select_ln52_fu_789_p3 == 5'd14) & ~(select_ln52_fu_789_p3 == 5'd15) & ~(select_ln52_fu_789_p3 == 5'd16) & ~(select_ln52_fu_789_p3 == 5'd17) & ~(select_ln52_fu_789_p3 == 5'd18) & ~(select_ln52_fu_789_p3 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_20_we0_local = 1'b1;
    end else begin
        X_buf_re_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_2_ce0_local = 1'b1;
    end else begin
        X_buf_re_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_2_we0_local = 1'b1;
    end else begin
        X_buf_re_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_3_ce0_local = 1'b1;
    end else begin
        X_buf_re_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_3_we0_local = 1'b1;
    end else begin
        X_buf_re_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_4_ce0_local = 1'b1;
    end else begin
        X_buf_re_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_4_we0_local = 1'b1;
    end else begin
        X_buf_re_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_5_ce0_local = 1'b1;
    end else begin
        X_buf_re_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_5_we0_local = 1'b1;
    end else begin
        X_buf_re_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_6_ce0_local = 1'b1;
    end else begin
        X_buf_re_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_6_we0_local = 1'b1;
    end else begin
        X_buf_re_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_7_ce0_local = 1'b1;
    end else begin
        X_buf_re_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_7_we0_local = 1'b1;
    end else begin
        X_buf_re_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_8_ce0_local = 1'b1;
    end else begin
        X_buf_re_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_8_we0_local = 1'b1;
    end else begin
        X_buf_re_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_9_ce0_local = 1'b1;
    end else begin
        X_buf_re_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_9_we0_local = 1'b1;
    end else begin
        X_buf_re_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_ce0_local = 1'b1;
    end else begin
        X_buf_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln52_fu_789_p3 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_we0_local = 1'b1;
    end else begin
        X_buf_re_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_766_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_180;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_in_TDATA_blk_n = y_in_TVALID;
    end else begin
        y_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_in_TREADY = 1'b1;
    end else begin
        y_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_buf_im_10_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_10_ce0 = X_buf_im_10_ce0_local;

assign X_buf_im_10_d0 = xi_fu_889_p1;

assign X_buf_im_10_we0 = X_buf_im_10_we0_local;

assign X_buf_im_11_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_11_ce0 = X_buf_im_11_ce0_local;

assign X_buf_im_11_d0 = xi_fu_889_p1;

assign X_buf_im_11_we0 = X_buf_im_11_we0_local;

assign X_buf_im_12_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_12_ce0 = X_buf_im_12_ce0_local;

assign X_buf_im_12_d0 = xi_fu_889_p1;

assign X_buf_im_12_we0 = X_buf_im_12_we0_local;

assign X_buf_im_13_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_13_ce0 = X_buf_im_13_ce0_local;

assign X_buf_im_13_d0 = xi_fu_889_p1;

assign X_buf_im_13_we0 = X_buf_im_13_we0_local;

assign X_buf_im_14_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_14_ce0 = X_buf_im_14_ce0_local;

assign X_buf_im_14_d0 = xi_fu_889_p1;

assign X_buf_im_14_we0 = X_buf_im_14_we0_local;

assign X_buf_im_15_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_15_ce0 = X_buf_im_15_ce0_local;

assign X_buf_im_15_d0 = xi_fu_889_p1;

assign X_buf_im_15_we0 = X_buf_im_15_we0_local;

assign X_buf_im_16_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_16_ce0 = X_buf_im_16_ce0_local;

assign X_buf_im_16_d0 = xi_fu_889_p1;

assign X_buf_im_16_we0 = X_buf_im_16_we0_local;

assign X_buf_im_17_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_17_ce0 = X_buf_im_17_ce0_local;

assign X_buf_im_17_d0 = xi_fu_889_p1;

assign X_buf_im_17_we0 = X_buf_im_17_we0_local;

assign X_buf_im_18_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_18_ce0 = X_buf_im_18_ce0_local;

assign X_buf_im_18_d0 = xi_fu_889_p1;

assign X_buf_im_18_we0 = X_buf_im_18_we0_local;

assign X_buf_im_19_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_19_ce0 = X_buf_im_19_ce0_local;

assign X_buf_im_19_d0 = xi_fu_889_p1;

assign X_buf_im_19_we0 = X_buf_im_19_we0_local;

assign X_buf_im_1_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_1_ce0 = X_buf_im_1_ce0_local;

assign X_buf_im_1_d0 = xi_fu_889_p1;

assign X_buf_im_1_we0 = X_buf_im_1_we0_local;

assign X_buf_im_20_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_20_ce0 = X_buf_im_20_ce0_local;

assign X_buf_im_20_d0 = xi_fu_889_p1;

assign X_buf_im_20_we0 = X_buf_im_20_we0_local;

assign X_buf_im_2_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_2_ce0 = X_buf_im_2_ce0_local;

assign X_buf_im_2_d0 = xi_fu_889_p1;

assign X_buf_im_2_we0 = X_buf_im_2_we0_local;

assign X_buf_im_3_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_3_ce0 = X_buf_im_3_ce0_local;

assign X_buf_im_3_d0 = xi_fu_889_p1;

assign X_buf_im_3_we0 = X_buf_im_3_we0_local;

assign X_buf_im_4_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_4_ce0 = X_buf_im_4_ce0_local;

assign X_buf_im_4_d0 = xi_fu_889_p1;

assign X_buf_im_4_we0 = X_buf_im_4_we0_local;

assign X_buf_im_5_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_5_ce0 = X_buf_im_5_ce0_local;

assign X_buf_im_5_d0 = xi_fu_889_p1;

assign X_buf_im_5_we0 = X_buf_im_5_we0_local;

assign X_buf_im_6_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_6_ce0 = X_buf_im_6_ce0_local;

assign X_buf_im_6_d0 = xi_fu_889_p1;

assign X_buf_im_6_we0 = X_buf_im_6_we0_local;

assign X_buf_im_7_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_7_ce0 = X_buf_im_7_ce0_local;

assign X_buf_im_7_d0 = xi_fu_889_p1;

assign X_buf_im_7_we0 = X_buf_im_7_we0_local;

assign X_buf_im_8_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_8_ce0 = X_buf_im_8_ce0_local;

assign X_buf_im_8_d0 = xi_fu_889_p1;

assign X_buf_im_8_we0 = X_buf_im_8_we0_local;

assign X_buf_im_9_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_9_ce0 = X_buf_im_9_ce0_local;

assign X_buf_im_9_d0 = xi_fu_889_p1;

assign X_buf_im_9_we0 = X_buf_im_9_we0_local;

assign X_buf_im_address0 = zext_ln52_fu_811_p1;

assign X_buf_im_ce0 = X_buf_im_ce0_local;

assign X_buf_im_d0 = xi_fu_889_p1;

assign X_buf_im_we0 = X_buf_im_we0_local;

assign X_buf_re_10_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_10_ce0 = X_buf_re_10_ce0_local;

assign X_buf_re_10_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_10_we0 = X_buf_re_10_we0_local;

assign X_buf_re_11_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_11_ce0 = X_buf_re_11_ce0_local;

assign X_buf_re_11_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_11_we0 = X_buf_re_11_we0_local;

assign X_buf_re_12_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_12_ce0 = X_buf_re_12_ce0_local;

assign X_buf_re_12_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_12_we0 = X_buf_re_12_we0_local;

assign X_buf_re_13_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_13_ce0 = X_buf_re_13_ce0_local;

assign X_buf_re_13_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_13_we0 = X_buf_re_13_we0_local;

assign X_buf_re_14_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_14_ce0 = X_buf_re_14_ce0_local;

assign X_buf_re_14_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_14_we0 = X_buf_re_14_we0_local;

assign X_buf_re_15_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_15_ce0 = X_buf_re_15_ce0_local;

assign X_buf_re_15_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_15_we0 = X_buf_re_15_we0_local;

assign X_buf_re_16_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_16_ce0 = X_buf_re_16_ce0_local;

assign X_buf_re_16_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_16_we0 = X_buf_re_16_we0_local;

assign X_buf_re_17_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_17_ce0 = X_buf_re_17_ce0_local;

assign X_buf_re_17_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_17_we0 = X_buf_re_17_we0_local;

assign X_buf_re_18_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_18_ce0 = X_buf_re_18_ce0_local;

assign X_buf_re_18_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_18_we0 = X_buf_re_18_we0_local;

assign X_buf_re_19_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_19_ce0 = X_buf_re_19_ce0_local;

assign X_buf_re_19_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_19_we0 = X_buf_re_19_we0_local;

assign X_buf_re_1_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_1_ce0 = X_buf_re_1_ce0_local;

assign X_buf_re_1_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_1_we0 = X_buf_re_1_we0_local;

assign X_buf_re_20_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_20_ce0 = X_buf_re_20_ce0_local;

assign X_buf_re_20_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_20_we0 = X_buf_re_20_we0_local;

assign X_buf_re_2_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_2_ce0 = X_buf_re_2_ce0_local;

assign X_buf_re_2_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_2_we0 = X_buf_re_2_we0_local;

assign X_buf_re_3_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_3_ce0 = X_buf_re_3_ce0_local;

assign X_buf_re_3_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_3_we0 = X_buf_re_3_we0_local;

assign X_buf_re_4_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_4_ce0 = X_buf_re_4_ce0_local;

assign X_buf_re_4_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_4_we0 = X_buf_re_4_we0_local;

assign X_buf_re_5_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_5_ce0 = X_buf_re_5_ce0_local;

assign X_buf_re_5_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_5_we0 = X_buf_re_5_we0_local;

assign X_buf_re_6_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_6_ce0 = X_buf_re_6_ce0_local;

assign X_buf_re_6_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_6_we0 = X_buf_re_6_we0_local;

assign X_buf_re_7_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_7_ce0 = X_buf_re_7_ce0_local;

assign X_buf_re_7_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_7_we0 = X_buf_re_7_we0_local;

assign X_buf_re_8_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_8_ce0 = X_buf_re_8_ce0_local;

assign X_buf_re_8_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_8_we0 = X_buf_re_8_we0_local;

assign X_buf_re_9_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_9_ce0 = X_buf_re_9_ce0_local;

assign X_buf_re_9_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_9_we0 = X_buf_re_9_we0_local;

assign X_buf_re_address0 = zext_ln52_fu_811_p1;

assign X_buf_re_ce0 = X_buf_re_ce0_local;

assign X_buf_re_d0 = {{y_in_TDATA[31:16]}};

assign X_buf_re_we0 = X_buf_re_we0_local;

assign add_ln52_1_fu_797_p2 = (t_fu_176 + 10'd1);

assign add_ln52_fu_760_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln54_fu_1127_p2 = (select_ln52_fu_789_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((y_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((y_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((y_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln52_fu_766_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd21000) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_783_p2 = ((ch_fu_172 == 5'd21) ? 1'b1 : 1'b0);

assign select_ln52_1_fu_803_p3 = ((icmp_ln54_fu_783_p2[0:0] == 1'b1) ? add_ln52_1_fu_797_p2 : t_fu_176);

assign select_ln52_fu_789_p3 = ((icmp_ln54_fu_783_p2[0:0] == 1'b1) ? 5'd0 : ch_fu_172);

assign xi_fu_889_p1 = y_in_TDATA[15:0];

assign zext_ln52_fu_811_p1 = select_ln52_1_fu_803_p3;

endmodule //covariance_estimation_covariance_estimation_Pipeline_LOAD_SNAPSHOT_LOAD_CHANNEL
