// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module covariance_estimation_covariance_estimation_Pipeline_INNER_K (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_buf_re_address0,
        X_buf_re_ce0,
        X_buf_re_q0,
        X_buf_re_1_address0,
        X_buf_re_1_ce0,
        X_buf_re_1_q0,
        X_buf_re_2_address0,
        X_buf_re_2_ce0,
        X_buf_re_2_q0,
        X_buf_re_3_address0,
        X_buf_re_3_ce0,
        X_buf_re_3_q0,
        X_buf_re_4_address0,
        X_buf_re_4_ce0,
        X_buf_re_4_q0,
        X_buf_re_5_address0,
        X_buf_re_5_ce0,
        X_buf_re_5_q0,
        X_buf_re_6_address0,
        X_buf_re_6_ce0,
        X_buf_re_6_q0,
        X_buf_re_7_address0,
        X_buf_re_7_ce0,
        X_buf_re_7_q0,
        X_buf_re_8_address0,
        X_buf_re_8_ce0,
        X_buf_re_8_q0,
        X_buf_re_9_address0,
        X_buf_re_9_ce0,
        X_buf_re_9_q0,
        X_buf_re_10_address0,
        X_buf_re_10_ce0,
        X_buf_re_10_q0,
        X_buf_re_11_address0,
        X_buf_re_11_ce0,
        X_buf_re_11_q0,
        X_buf_re_12_address0,
        X_buf_re_12_ce0,
        X_buf_re_12_q0,
        X_buf_re_13_address0,
        X_buf_re_13_ce0,
        X_buf_re_13_q0,
        X_buf_re_14_address0,
        X_buf_re_14_ce0,
        X_buf_re_14_q0,
        X_buf_re_15_address0,
        X_buf_re_15_ce0,
        X_buf_re_15_q0,
        X_buf_re_16_address0,
        X_buf_re_16_ce0,
        X_buf_re_16_q0,
        X_buf_re_17_address0,
        X_buf_re_17_ce0,
        X_buf_re_17_q0,
        X_buf_re_18_address0,
        X_buf_re_18_ce0,
        X_buf_re_18_q0,
        X_buf_re_19_address0,
        X_buf_re_19_ce0,
        X_buf_re_19_q0,
        X_buf_re_20_address0,
        X_buf_re_20_ce0,
        X_buf_re_20_q0,
        j_3,
        X_buf_im_address0,
        X_buf_im_ce0,
        X_buf_im_q0,
        X_buf_im_1_address0,
        X_buf_im_1_ce0,
        X_buf_im_1_q0,
        X_buf_im_2_address0,
        X_buf_im_2_ce0,
        X_buf_im_2_q0,
        X_buf_im_3_address0,
        X_buf_im_3_ce0,
        X_buf_im_3_q0,
        X_buf_im_4_address0,
        X_buf_im_4_ce0,
        X_buf_im_4_q0,
        X_buf_im_5_address0,
        X_buf_im_5_ce0,
        X_buf_im_5_q0,
        X_buf_im_6_address0,
        X_buf_im_6_ce0,
        X_buf_im_6_q0,
        X_buf_im_7_address0,
        X_buf_im_7_ce0,
        X_buf_im_7_q0,
        X_buf_im_8_address0,
        X_buf_im_8_ce0,
        X_buf_im_8_q0,
        X_buf_im_9_address0,
        X_buf_im_9_ce0,
        X_buf_im_9_q0,
        X_buf_im_10_address0,
        X_buf_im_10_ce0,
        X_buf_im_10_q0,
        X_buf_im_11_address0,
        X_buf_im_11_ce0,
        X_buf_im_11_q0,
        X_buf_im_12_address0,
        X_buf_im_12_ce0,
        X_buf_im_12_q0,
        X_buf_im_13_address0,
        X_buf_im_13_ce0,
        X_buf_im_13_q0,
        X_buf_im_14_address0,
        X_buf_im_14_ce0,
        X_buf_im_14_q0,
        X_buf_im_15_address0,
        X_buf_im_15_ce0,
        X_buf_im_15_q0,
        X_buf_im_16_address0,
        X_buf_im_16_ce0,
        X_buf_im_16_q0,
        X_buf_im_17_address0,
        X_buf_im_17_ce0,
        X_buf_im_17_q0,
        X_buf_im_18_address0,
        X_buf_im_18_ce0,
        X_buf_im_18_q0,
        X_buf_im_19_address0,
        X_buf_im_19_ce0,
        X_buf_im_19_q0,
        X_buf_im_20_address0,
        X_buf_im_20_ce0,
        X_buf_im_20_q0,
        j,
        acc_im_out,
        acc_im_out_ap_vld,
        acc_re_out,
        acc_re_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] X_buf_re_address0;
output   X_buf_re_ce0;
input  [15:0] X_buf_re_q0;
output  [9:0] X_buf_re_1_address0;
output   X_buf_re_1_ce0;
input  [15:0] X_buf_re_1_q0;
output  [9:0] X_buf_re_2_address0;
output   X_buf_re_2_ce0;
input  [15:0] X_buf_re_2_q0;
output  [9:0] X_buf_re_3_address0;
output   X_buf_re_3_ce0;
input  [15:0] X_buf_re_3_q0;
output  [9:0] X_buf_re_4_address0;
output   X_buf_re_4_ce0;
input  [15:0] X_buf_re_4_q0;
output  [9:0] X_buf_re_5_address0;
output   X_buf_re_5_ce0;
input  [15:0] X_buf_re_5_q0;
output  [9:0] X_buf_re_6_address0;
output   X_buf_re_6_ce0;
input  [15:0] X_buf_re_6_q0;
output  [9:0] X_buf_re_7_address0;
output   X_buf_re_7_ce0;
input  [15:0] X_buf_re_7_q0;
output  [9:0] X_buf_re_8_address0;
output   X_buf_re_8_ce0;
input  [15:0] X_buf_re_8_q0;
output  [9:0] X_buf_re_9_address0;
output   X_buf_re_9_ce0;
input  [15:0] X_buf_re_9_q0;
output  [9:0] X_buf_re_10_address0;
output   X_buf_re_10_ce0;
input  [15:0] X_buf_re_10_q0;
output  [9:0] X_buf_re_11_address0;
output   X_buf_re_11_ce0;
input  [15:0] X_buf_re_11_q0;
output  [9:0] X_buf_re_12_address0;
output   X_buf_re_12_ce0;
input  [15:0] X_buf_re_12_q0;
output  [9:0] X_buf_re_13_address0;
output   X_buf_re_13_ce0;
input  [15:0] X_buf_re_13_q0;
output  [9:0] X_buf_re_14_address0;
output   X_buf_re_14_ce0;
input  [15:0] X_buf_re_14_q0;
output  [9:0] X_buf_re_15_address0;
output   X_buf_re_15_ce0;
input  [15:0] X_buf_re_15_q0;
output  [9:0] X_buf_re_16_address0;
output   X_buf_re_16_ce0;
input  [15:0] X_buf_re_16_q0;
output  [9:0] X_buf_re_17_address0;
output   X_buf_re_17_ce0;
input  [15:0] X_buf_re_17_q0;
output  [9:0] X_buf_re_18_address0;
output   X_buf_re_18_ce0;
input  [15:0] X_buf_re_18_q0;
output  [9:0] X_buf_re_19_address0;
output   X_buf_re_19_ce0;
input  [15:0] X_buf_re_19_q0;
output  [9:0] X_buf_re_20_address0;
output   X_buf_re_20_ce0;
input  [15:0] X_buf_re_20_q0;
input  [4:0] j_3;
output  [9:0] X_buf_im_address0;
output   X_buf_im_ce0;
input  [15:0] X_buf_im_q0;
output  [9:0] X_buf_im_1_address0;
output   X_buf_im_1_ce0;
input  [15:0] X_buf_im_1_q0;
output  [9:0] X_buf_im_2_address0;
output   X_buf_im_2_ce0;
input  [15:0] X_buf_im_2_q0;
output  [9:0] X_buf_im_3_address0;
output   X_buf_im_3_ce0;
input  [15:0] X_buf_im_3_q0;
output  [9:0] X_buf_im_4_address0;
output   X_buf_im_4_ce0;
input  [15:0] X_buf_im_4_q0;
output  [9:0] X_buf_im_5_address0;
output   X_buf_im_5_ce0;
input  [15:0] X_buf_im_5_q0;
output  [9:0] X_buf_im_6_address0;
output   X_buf_im_6_ce0;
input  [15:0] X_buf_im_6_q0;
output  [9:0] X_buf_im_7_address0;
output   X_buf_im_7_ce0;
input  [15:0] X_buf_im_7_q0;
output  [9:0] X_buf_im_8_address0;
output   X_buf_im_8_ce0;
input  [15:0] X_buf_im_8_q0;
output  [9:0] X_buf_im_9_address0;
output   X_buf_im_9_ce0;
input  [15:0] X_buf_im_9_q0;
output  [9:0] X_buf_im_10_address0;
output   X_buf_im_10_ce0;
input  [15:0] X_buf_im_10_q0;
output  [9:0] X_buf_im_11_address0;
output   X_buf_im_11_ce0;
input  [15:0] X_buf_im_11_q0;
output  [9:0] X_buf_im_12_address0;
output   X_buf_im_12_ce0;
input  [15:0] X_buf_im_12_q0;
output  [9:0] X_buf_im_13_address0;
output   X_buf_im_13_ce0;
input  [15:0] X_buf_im_13_q0;
output  [9:0] X_buf_im_14_address0;
output   X_buf_im_14_ce0;
input  [15:0] X_buf_im_14_q0;
output  [9:0] X_buf_im_15_address0;
output   X_buf_im_15_ce0;
input  [15:0] X_buf_im_15_q0;
output  [9:0] X_buf_im_16_address0;
output   X_buf_im_16_ce0;
input  [15:0] X_buf_im_16_q0;
output  [9:0] X_buf_im_17_address0;
output   X_buf_im_17_ce0;
input  [15:0] X_buf_im_17_q0;
output  [9:0] X_buf_im_18_address0;
output   X_buf_im_18_ce0;
input  [15:0] X_buf_im_18_q0;
output  [9:0] X_buf_im_19_address0;
output   X_buf_im_19_ce0;
input  [15:0] X_buf_im_19_q0;
output  [9:0] X_buf_im_20_address0;
output   X_buf_im_20_ce0;
input  [15:0] X_buf_im_20_q0;
input  [4:0] j;
output  [47:0] acc_im_out;
output   acc_im_out_ap_vld;
output  [47:0] acc_re_out;
output   acc_re_out_ap_vld;

reg ap_idle;
reg acc_im_out_ap_vld;
reg acc_re_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln82_fu_796_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln82_reg_1669;
reg   [0:0] icmp_ln82_reg_1669_pp0_iter1_reg;
reg   [0:0] icmp_ln82_reg_1669_pp0_iter2_reg;
wire   [15:0] a_im_fu_1112_p45;
reg   [15:0] a_im_reg_1883;
wire  signed [31:0] sext_ln18_fu_1385_p1;
wire  signed [31:0] sext_ln18_1_fu_1389_p1;
reg  signed [31:0] sext_ln18_1_reg_1894;
wire  signed [31:0] sext_ln18_3_fu_1401_p1;
reg  signed [31:0] sext_ln18_3_reg_1901;
wire   [31:0] mul_ln18_1_fu_1423_p2;
reg  signed [31:0] mul_ln18_1_reg_1908;
wire   [31:0] mul_ln19_fu_1435_p2;
reg  signed [31:0] mul_ln19_reg_1913;
wire   [63:0] zext_ln82_fu_802_p1;
wire    ap_block_pp0_stage0;
reg   [47:0] acc_re_fu_188;
wire   [47:0] acc_re_2_fu_1516_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [47:0] acc_im_fu_192;
wire   [47:0] acc_im_2_fu_1591_p3;
reg   [9:0] t_fu_196;
wire   [9:0] add_ln82_fu_790_p2;
reg   [9:0] ap_sig_allocacmp_t_1;
wire    ap_block_pp0_stage0_01001;
reg    X_buf_re_ce0_local;
reg    X_buf_re_1_ce0_local;
reg    X_buf_re_2_ce0_local;
reg    X_buf_re_3_ce0_local;
reg    X_buf_re_4_ce0_local;
reg    X_buf_re_5_ce0_local;
reg    X_buf_re_6_ce0_local;
reg    X_buf_re_7_ce0_local;
reg    X_buf_re_8_ce0_local;
reg    X_buf_re_9_ce0_local;
reg    X_buf_re_10_ce0_local;
reg    X_buf_re_11_ce0_local;
reg    X_buf_re_12_ce0_local;
reg    X_buf_re_13_ce0_local;
reg    X_buf_re_14_ce0_local;
reg    X_buf_re_15_ce0_local;
reg    X_buf_re_16_ce0_local;
reg    X_buf_re_17_ce0_local;
reg    X_buf_re_18_ce0_local;
reg    X_buf_re_19_ce0_local;
reg    X_buf_re_20_ce0_local;
reg    X_buf_im_ce0_local;
reg    X_buf_im_1_ce0_local;
reg    X_buf_im_2_ce0_local;
reg    X_buf_im_3_ce0_local;
reg    X_buf_im_4_ce0_local;
reg    X_buf_im_5_ce0_local;
reg    X_buf_im_6_ce0_local;
reg    X_buf_im_7_ce0_local;
reg    X_buf_im_8_ce0_local;
reg    X_buf_im_9_ce0_local;
reg    X_buf_im_10_ce0_local;
reg    X_buf_im_11_ce0_local;
reg    X_buf_im_12_ce0_local;
reg    X_buf_im_13_ce0_local;
reg    X_buf_im_14_ce0_local;
reg    X_buf_im_15_ce0_local;
reg    X_buf_im_16_ce0_local;
reg    X_buf_im_17_ce0_local;
reg    X_buf_im_18_ce0_local;
reg    X_buf_im_19_ce0_local;
reg    X_buf_im_20_ce0_local;
wire   [15:0] a_re_fu_1021_p43;
wire   [15:0] a_im_fu_1112_p43;
wire   [15:0] b_re_fu_1203_p43;
wire   [15:0] b_im_fu_1294_p43;
wire   [15:0] a_re_fu_1021_p45;
wire  signed [15:0] b_re_fu_1203_p45;
wire  signed [15:0] b_im_fu_1294_p45;
wire  signed [15:0] mul_ln18_1_fu_1423_p0;
wire  signed [15:0] mul_ln18_1_fu_1423_p1;
wire  signed [31:0] sext_ln18_2_fu_1413_p1;
wire  signed [15:0] mul_ln19_fu_1435_p0;
wire  signed [15:0] mul_ln19_fu_1435_p1;
wire  signed [47:0] sext_ln18_6_fu_1449_p0;
wire  signed [32:0] grp_fu_1617_p3;
wire   [38:0] shl_ln_fu_1453_p3;
wire  signed [48:0] sext_ln18_7_fu_1460_p1;
wire  signed [48:0] sext_ln18_6_fu_1449_p1;
wire   [48:0] add_ln18_1_fu_1464_p2;
wire   [0:0] tmp_fu_1470_p3;
wire   [0:0] tmp_5_fu_1482_p3;
wire   [0:0] xor_ln18_fu_1490_p2;
wire   [0:0] and_ln18_fu_1496_p2;
wire   [0:0] xor_ln18_1_fu_1502_p2;
wire   [47:0] select_ln18_fu_1508_p3;
wire   [47:0] acc_re_1_fu_1478_p1;
wire  signed [47:0] sext_ln19_fu_1524_p0;
wire  signed [31:0] grp_fu_1626_p3;
wire   [37:0] shl_ln1_fu_1528_p3;
wire  signed [48:0] sext_ln19_1_fu_1535_p1;
wire  signed [48:0] sext_ln19_fu_1524_p1;
wire   [48:0] add_ln19_fu_1539_p2;
wire   [0:0] tmp_6_fu_1545_p3;
wire   [0:0] tmp_7_fu_1557_p3;
wire   [0:0] xor_ln19_fu_1565_p2;
wire   [0:0] and_ln19_fu_1571_p2;
wire   [0:0] xor_ln19_1_fu_1577_p2;
wire   [47:0] select_ln19_fu_1583_p3;
wire   [47:0] acc_im_1_fu_1553_p1;
wire  signed [15:0] grp_fu_1617_p1;
wire  signed [15:0] grp_fu_1626_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] a_re_fu_1021_p1;
wire   [4:0] a_re_fu_1021_p3;
wire   [4:0] a_re_fu_1021_p5;
wire   [4:0] a_re_fu_1021_p7;
wire   [4:0] a_re_fu_1021_p9;
wire   [4:0] a_re_fu_1021_p11;
wire   [4:0] a_re_fu_1021_p13;
wire   [4:0] a_re_fu_1021_p15;
wire   [4:0] a_re_fu_1021_p17;
wire   [4:0] a_re_fu_1021_p19;
wire   [4:0] a_re_fu_1021_p21;
wire   [4:0] a_re_fu_1021_p23;
wire   [4:0] a_re_fu_1021_p25;
wire   [4:0] a_re_fu_1021_p27;
wire   [4:0] a_re_fu_1021_p29;
wire   [4:0] a_re_fu_1021_p31;
wire  signed [4:0] a_re_fu_1021_p33;
wire  signed [4:0] a_re_fu_1021_p35;
wire  signed [4:0] a_re_fu_1021_p37;
wire  signed [4:0] a_re_fu_1021_p39;
wire  signed [4:0] a_re_fu_1021_p41;
wire   [4:0] a_im_fu_1112_p1;
wire   [4:0] a_im_fu_1112_p3;
wire   [4:0] a_im_fu_1112_p5;
wire   [4:0] a_im_fu_1112_p7;
wire   [4:0] a_im_fu_1112_p9;
wire   [4:0] a_im_fu_1112_p11;
wire   [4:0] a_im_fu_1112_p13;
wire   [4:0] a_im_fu_1112_p15;
wire   [4:0] a_im_fu_1112_p17;
wire   [4:0] a_im_fu_1112_p19;
wire   [4:0] a_im_fu_1112_p21;
wire   [4:0] a_im_fu_1112_p23;
wire   [4:0] a_im_fu_1112_p25;
wire   [4:0] a_im_fu_1112_p27;
wire   [4:0] a_im_fu_1112_p29;
wire   [4:0] a_im_fu_1112_p31;
wire  signed [4:0] a_im_fu_1112_p33;
wire  signed [4:0] a_im_fu_1112_p35;
wire  signed [4:0] a_im_fu_1112_p37;
wire  signed [4:0] a_im_fu_1112_p39;
wire  signed [4:0] a_im_fu_1112_p41;
wire   [4:0] b_re_fu_1203_p1;
wire   [4:0] b_re_fu_1203_p3;
wire   [4:0] b_re_fu_1203_p5;
wire   [4:0] b_re_fu_1203_p7;
wire   [4:0] b_re_fu_1203_p9;
wire   [4:0] b_re_fu_1203_p11;
wire   [4:0] b_re_fu_1203_p13;
wire   [4:0] b_re_fu_1203_p15;
wire   [4:0] b_re_fu_1203_p17;
wire   [4:0] b_re_fu_1203_p19;
wire   [4:0] b_re_fu_1203_p21;
wire   [4:0] b_re_fu_1203_p23;
wire   [4:0] b_re_fu_1203_p25;
wire   [4:0] b_re_fu_1203_p27;
wire   [4:0] b_re_fu_1203_p29;
wire   [4:0] b_re_fu_1203_p31;
wire  signed [4:0] b_re_fu_1203_p33;
wire  signed [4:0] b_re_fu_1203_p35;
wire  signed [4:0] b_re_fu_1203_p37;
wire  signed [4:0] b_re_fu_1203_p39;
wire  signed [4:0] b_re_fu_1203_p41;
wire   [4:0] b_im_fu_1294_p1;
wire   [4:0] b_im_fu_1294_p3;
wire   [4:0] b_im_fu_1294_p5;
wire   [4:0] b_im_fu_1294_p7;
wire   [4:0] b_im_fu_1294_p9;
wire   [4:0] b_im_fu_1294_p11;
wire   [4:0] b_im_fu_1294_p13;
wire   [4:0] b_im_fu_1294_p15;
wire   [4:0] b_im_fu_1294_p17;
wire   [4:0] b_im_fu_1294_p19;
wire   [4:0] b_im_fu_1294_p21;
wire   [4:0] b_im_fu_1294_p23;
wire   [4:0] b_im_fu_1294_p25;
wire   [4:0] b_im_fu_1294_p27;
wire   [4:0] b_im_fu_1294_p29;
wire   [4:0] b_im_fu_1294_p31;
wire  signed [4:0] b_im_fu_1294_p33;
wire  signed [4:0] b_im_fu_1294_p35;
wire  signed [4:0] b_im_fu_1294_p37;
wire  signed [4:0] b_im_fu_1294_p39;
wire  signed [4:0] b_im_fu_1294_p41;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 acc_re_fu_188 = 48'd0;
#0 acc_im_fu_192 = 48'd0;
#0 t_fu_196 = 10'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_43_5_16_1_1_U44(
    .din0(X_buf_re_q0),
    .din1(X_buf_re_1_q0),
    .din2(X_buf_re_2_q0),
    .din3(X_buf_re_3_q0),
    .din4(X_buf_re_4_q0),
    .din5(X_buf_re_5_q0),
    .din6(X_buf_re_6_q0),
    .din7(X_buf_re_7_q0),
    .din8(X_buf_re_8_q0),
    .din9(X_buf_re_9_q0),
    .din10(X_buf_re_10_q0),
    .din11(X_buf_re_11_q0),
    .din12(X_buf_re_12_q0),
    .din13(X_buf_re_13_q0),
    .din14(X_buf_re_14_q0),
    .din15(X_buf_re_15_q0),
    .din16(X_buf_re_16_q0),
    .din17(X_buf_re_17_q0),
    .din18(X_buf_re_18_q0),
    .din19(X_buf_re_19_q0),
    .din20(X_buf_re_20_q0),
    .def(a_re_fu_1021_p43),
    .sel(j_3),
    .dout(a_re_fu_1021_p45)
);

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_43_5_16_1_1_U45(
    .din0(X_buf_im_q0),
    .din1(X_buf_im_1_q0),
    .din2(X_buf_im_2_q0),
    .din3(X_buf_im_3_q0),
    .din4(X_buf_im_4_q0),
    .din5(X_buf_im_5_q0),
    .din6(X_buf_im_6_q0),
    .din7(X_buf_im_7_q0),
    .din8(X_buf_im_8_q0),
    .din9(X_buf_im_9_q0),
    .din10(X_buf_im_10_q0),
    .din11(X_buf_im_11_q0),
    .din12(X_buf_im_12_q0),
    .din13(X_buf_im_13_q0),
    .din14(X_buf_im_14_q0),
    .din15(X_buf_im_15_q0),
    .din16(X_buf_im_16_q0),
    .din17(X_buf_im_17_q0),
    .din18(X_buf_im_18_q0),
    .din19(X_buf_im_19_q0),
    .din20(X_buf_im_20_q0),
    .def(a_im_fu_1112_p43),
    .sel(j_3),
    .dout(a_im_fu_1112_p45)
);

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_43_5_16_1_1_U46(
    .din0(X_buf_re_q0),
    .din1(X_buf_re_1_q0),
    .din2(X_buf_re_2_q0),
    .din3(X_buf_re_3_q0),
    .din4(X_buf_re_4_q0),
    .din5(X_buf_re_5_q0),
    .din6(X_buf_re_6_q0),
    .din7(X_buf_re_7_q0),
    .din8(X_buf_re_8_q0),
    .din9(X_buf_re_9_q0),
    .din10(X_buf_re_10_q0),
    .din11(X_buf_re_11_q0),
    .din12(X_buf_re_12_q0),
    .din13(X_buf_re_13_q0),
    .din14(X_buf_re_14_q0),
    .din15(X_buf_re_15_q0),
    .din16(X_buf_re_16_q0),
    .din17(X_buf_re_17_q0),
    .din18(X_buf_re_18_q0),
    .din19(X_buf_re_19_q0),
    .din20(X_buf_re_20_q0),
    .def(b_re_fu_1203_p43),
    .sel(j),
    .dout(b_re_fu_1203_p45)
);

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_43_5_16_1_1_U47(
    .din0(X_buf_im_q0),
    .din1(X_buf_im_1_q0),
    .din2(X_buf_im_2_q0),
    .din3(X_buf_im_3_q0),
    .din4(X_buf_im_4_q0),
    .din5(X_buf_im_5_q0),
    .din6(X_buf_im_6_q0),
    .din7(X_buf_im_7_q0),
    .din8(X_buf_im_8_q0),
    .din9(X_buf_im_9_q0),
    .din10(X_buf_im_10_q0),
    .din11(X_buf_im_11_q0),
    .din12(X_buf_im_12_q0),
    .din13(X_buf_im_13_q0),
    .din14(X_buf_im_14_q0),
    .din15(X_buf_im_15_q0),
    .din16(X_buf_im_16_q0),
    .din17(X_buf_im_17_q0),
    .din18(X_buf_im_18_q0),
    .din19(X_buf_im_19_q0),
    .din20(X_buf_im_20_q0),
    .def(b_im_fu_1294_p43),
    .sel(j),
    .dout(b_im_fu_1294_p45)
);

covariance_estimation_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U48(
    .din0(mul_ln18_1_fu_1423_p0),
    .din1(mul_ln18_1_fu_1423_p1),
    .dout(mul_ln18_1_fu_1423_p2)
);

covariance_estimation_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U49(
    .din0(mul_ln19_fu_1435_p0),
    .din1(mul_ln19_fu_1435_p1),
    .dout(mul_ln19_fu_1435_p2)
);

covariance_estimation_mac_muladd_16s_16s_32s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 33 ))
mac_muladd_16s_16s_32s_33_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_re_fu_1203_p45),
    .din1(grp_fu_1617_p1),
    .din2(mul_ln18_1_reg_1908),
    .ce(1'b1),
    .dout(grp_fu_1617_p3)
);

covariance_estimation_mac_mulsub_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_16s_16s_32s_32_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_im_fu_1294_p45),
    .din1(grp_fu_1626_p1),
    .din2(mul_ln19_reg_1913),
    .ce(1'b1),
    .dout(grp_fu_1626_p3)
);

covariance_estimation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_im_fu_192 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            acc_im_fu_192 <= acc_im_2_fu_1591_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_re_fu_188 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            acc_re_fu_188 <= acc_re_2_fu_1516_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln82_fu_796_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_196 <= add_ln82_fu_790_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_196 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_im_reg_1883 <= a_im_fu_1112_p45;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln82_reg_1669 <= icmp_ln82_fu_796_p2;
        icmp_ln82_reg_1669_pp0_iter1_reg <= icmp_ln82_reg_1669;
        sext_ln18_1_reg_1894 <= sext_ln18_1_fu_1389_p1;
        sext_ln18_3_reg_1901 <= sext_ln18_3_fu_1401_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln82_reg_1669_pp0_iter2_reg <= icmp_ln82_reg_1669_pp0_iter1_reg;
        mul_ln18_1_reg_1908 <= mul_ln18_1_fu_1423_p2;
        mul_ln19_reg_1913 <= mul_ln19_fu_1435_p2;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_10_ce0_local = 1'b1;
    end else begin
        X_buf_im_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_11_ce0_local = 1'b1;
    end else begin
        X_buf_im_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_12_ce0_local = 1'b1;
    end else begin
        X_buf_im_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_13_ce0_local = 1'b1;
    end else begin
        X_buf_im_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_14_ce0_local = 1'b1;
    end else begin
        X_buf_im_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_15_ce0_local = 1'b1;
    end else begin
        X_buf_im_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_16_ce0_local = 1'b1;
    end else begin
        X_buf_im_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_17_ce0_local = 1'b1;
    end else begin
        X_buf_im_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_18_ce0_local = 1'b1;
    end else begin
        X_buf_im_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_19_ce0_local = 1'b1;
    end else begin
        X_buf_im_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_1_ce0_local = 1'b1;
    end else begin
        X_buf_im_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_20_ce0_local = 1'b1;
    end else begin
        X_buf_im_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_2_ce0_local = 1'b1;
    end else begin
        X_buf_im_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_3_ce0_local = 1'b1;
    end else begin
        X_buf_im_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_4_ce0_local = 1'b1;
    end else begin
        X_buf_im_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_5_ce0_local = 1'b1;
    end else begin
        X_buf_im_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_6_ce0_local = 1'b1;
    end else begin
        X_buf_im_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_7_ce0_local = 1'b1;
    end else begin
        X_buf_im_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_8_ce0_local = 1'b1;
    end else begin
        X_buf_im_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_9_ce0_local = 1'b1;
    end else begin
        X_buf_im_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_im_ce0_local = 1'b1;
    end else begin
        X_buf_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_10_ce0_local = 1'b1;
    end else begin
        X_buf_re_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_11_ce0_local = 1'b1;
    end else begin
        X_buf_re_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_12_ce0_local = 1'b1;
    end else begin
        X_buf_re_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_13_ce0_local = 1'b1;
    end else begin
        X_buf_re_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_14_ce0_local = 1'b1;
    end else begin
        X_buf_re_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_15_ce0_local = 1'b1;
    end else begin
        X_buf_re_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_16_ce0_local = 1'b1;
    end else begin
        X_buf_re_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_17_ce0_local = 1'b1;
    end else begin
        X_buf_re_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_18_ce0_local = 1'b1;
    end else begin
        X_buf_re_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_19_ce0_local = 1'b1;
    end else begin
        X_buf_re_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_1_ce0_local = 1'b1;
    end else begin
        X_buf_re_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_20_ce0_local = 1'b1;
    end else begin
        X_buf_re_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_2_ce0_local = 1'b1;
    end else begin
        X_buf_re_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_3_ce0_local = 1'b1;
    end else begin
        X_buf_re_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_4_ce0_local = 1'b1;
    end else begin
        X_buf_re_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_5_ce0_local = 1'b1;
    end else begin
        X_buf_re_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_6_ce0_local = 1'b1;
    end else begin
        X_buf_re_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_7_ce0_local = 1'b1;
    end else begin
        X_buf_re_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_8_ce0_local = 1'b1;
    end else begin
        X_buf_re_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_9_ce0_local = 1'b1;
    end else begin
        X_buf_re_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_buf_re_ce0_local = 1'b1;
    end else begin
        X_buf_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln82_reg_1669_pp0_iter2_reg == 1'd1))) begin
        acc_im_out_ap_vld = 1'b1;
    end else begin
        acc_im_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln82_reg_1669_pp0_iter2_reg == 1'd1))) begin
        acc_re_out_ap_vld = 1'b1;
    end else begin
        acc_re_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_796_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_196;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_buf_im_10_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_10_ce0 = X_buf_im_10_ce0_local;

assign X_buf_im_11_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_11_ce0 = X_buf_im_11_ce0_local;

assign X_buf_im_12_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_12_ce0 = X_buf_im_12_ce0_local;

assign X_buf_im_13_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_13_ce0 = X_buf_im_13_ce0_local;

assign X_buf_im_14_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_14_ce0 = X_buf_im_14_ce0_local;

assign X_buf_im_15_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_15_ce0 = X_buf_im_15_ce0_local;

assign X_buf_im_16_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_16_ce0 = X_buf_im_16_ce0_local;

assign X_buf_im_17_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_17_ce0 = X_buf_im_17_ce0_local;

assign X_buf_im_18_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_18_ce0 = X_buf_im_18_ce0_local;

assign X_buf_im_19_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_19_ce0 = X_buf_im_19_ce0_local;

assign X_buf_im_1_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_1_ce0 = X_buf_im_1_ce0_local;

assign X_buf_im_20_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_20_ce0 = X_buf_im_20_ce0_local;

assign X_buf_im_2_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_2_ce0 = X_buf_im_2_ce0_local;

assign X_buf_im_3_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_3_ce0 = X_buf_im_3_ce0_local;

assign X_buf_im_4_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_4_ce0 = X_buf_im_4_ce0_local;

assign X_buf_im_5_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_5_ce0 = X_buf_im_5_ce0_local;

assign X_buf_im_6_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_6_ce0 = X_buf_im_6_ce0_local;

assign X_buf_im_7_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_7_ce0 = X_buf_im_7_ce0_local;

assign X_buf_im_8_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_8_ce0 = X_buf_im_8_ce0_local;

assign X_buf_im_9_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_9_ce0 = X_buf_im_9_ce0_local;

assign X_buf_im_address0 = zext_ln82_fu_802_p1;

assign X_buf_im_ce0 = X_buf_im_ce0_local;

assign X_buf_re_10_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_10_ce0 = X_buf_re_10_ce0_local;

assign X_buf_re_11_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_11_ce0 = X_buf_re_11_ce0_local;

assign X_buf_re_12_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_12_ce0 = X_buf_re_12_ce0_local;

assign X_buf_re_13_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_13_ce0 = X_buf_re_13_ce0_local;

assign X_buf_re_14_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_14_ce0 = X_buf_re_14_ce0_local;

assign X_buf_re_15_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_15_ce0 = X_buf_re_15_ce0_local;

assign X_buf_re_16_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_16_ce0 = X_buf_re_16_ce0_local;

assign X_buf_re_17_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_17_ce0 = X_buf_re_17_ce0_local;

assign X_buf_re_18_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_18_ce0 = X_buf_re_18_ce0_local;

assign X_buf_re_19_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_19_ce0 = X_buf_re_19_ce0_local;

assign X_buf_re_1_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_1_ce0 = X_buf_re_1_ce0_local;

assign X_buf_re_20_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_20_ce0 = X_buf_re_20_ce0_local;

assign X_buf_re_2_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_2_ce0 = X_buf_re_2_ce0_local;

assign X_buf_re_3_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_3_ce0 = X_buf_re_3_ce0_local;

assign X_buf_re_4_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_4_ce0 = X_buf_re_4_ce0_local;

assign X_buf_re_5_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_5_ce0 = X_buf_re_5_ce0_local;

assign X_buf_re_6_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_6_ce0 = X_buf_re_6_ce0_local;

assign X_buf_re_7_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_7_ce0 = X_buf_re_7_ce0_local;

assign X_buf_re_8_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_8_ce0 = X_buf_re_8_ce0_local;

assign X_buf_re_9_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_9_ce0 = X_buf_re_9_ce0_local;

assign X_buf_re_address0 = zext_ln82_fu_802_p1;

assign X_buf_re_ce0 = X_buf_re_ce0_local;

assign a_im_fu_1112_p43 = 'bx;

assign a_re_fu_1021_p43 = 'bx;

assign acc_im_1_fu_1553_p1 = add_ln19_fu_1539_p2[47:0];

assign acc_im_2_fu_1591_p3 = ((xor_ln19_1_fu_1577_p2[0:0] == 1'b1) ? select_ln19_fu_1583_p3 : acc_im_1_fu_1553_p1);

assign acc_im_out = acc_im_fu_192;

assign acc_re_1_fu_1478_p1 = add_ln18_1_fu_1464_p2[47:0];

assign acc_re_2_fu_1516_p3 = ((xor_ln18_1_fu_1502_p2[0:0] == 1'b1) ? select_ln18_fu_1508_p3 : acc_re_1_fu_1478_p1);

assign acc_re_out = acc_re_fu_188;

assign add_ln18_1_fu_1464_p2 = ($signed(sext_ln18_7_fu_1460_p1) + $signed(sext_ln18_6_fu_1449_p1));

assign add_ln19_fu_1539_p2 = ($signed(sext_ln19_1_fu_1535_p1) + $signed(sext_ln19_fu_1524_p1));

assign add_ln82_fu_790_p2 = (ap_sig_allocacmp_t_1 + 10'd1);

assign and_ln18_fu_1496_p2 = (xor_ln18_fu_1490_p2 & tmp_5_fu_1482_p3);

assign and_ln19_fu_1571_p2 = (xor_ln19_fu_1565_p2 & tmp_7_fu_1557_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_im_fu_1294_p43 = 'bx;

assign b_re_fu_1203_p43 = 'bx;

assign grp_fu_1617_p1 = sext_ln18_fu_1385_p1;

assign grp_fu_1626_p1 = sext_ln18_fu_1385_p1;

assign icmp_ln82_fu_796_p2 = ((ap_sig_allocacmp_t_1 == 10'd1000) ? 1'b1 : 1'b0);

assign mul_ln18_1_fu_1423_p0 = sext_ln18_3_reg_1901;

assign mul_ln18_1_fu_1423_p1 = sext_ln18_2_fu_1413_p1;

assign mul_ln19_fu_1435_p0 = sext_ln18_1_reg_1894;

assign mul_ln19_fu_1435_p1 = sext_ln18_2_fu_1413_p1;

assign select_ln18_fu_1508_p3 = ((and_ln18_fu_1496_p2[0:0] == 1'b1) ? 48'd140737488355327 : 48'd140737488355328);

assign select_ln19_fu_1583_p3 = ((and_ln19_fu_1571_p2[0:0] == 1'b1) ? 48'd140737488355327 : 48'd140737488355328);

assign sext_ln18_1_fu_1389_p1 = b_re_fu_1203_p45;

assign sext_ln18_2_fu_1413_p1 = $signed(a_im_reg_1883);

assign sext_ln18_3_fu_1401_p1 = b_im_fu_1294_p45;

assign sext_ln18_6_fu_1449_p0 = acc_re_fu_188;

assign sext_ln18_6_fu_1449_p1 = sext_ln18_6_fu_1449_p0;

assign sext_ln18_7_fu_1460_p1 = $signed(shl_ln_fu_1453_p3);

assign sext_ln18_fu_1385_p1 = $signed(a_re_fu_1021_p45);

assign sext_ln19_1_fu_1535_p1 = $signed(shl_ln1_fu_1528_p3);

assign sext_ln19_fu_1524_p0 = acc_im_fu_192;

assign sext_ln19_fu_1524_p1 = sext_ln19_fu_1524_p0;

assign shl_ln1_fu_1528_p3 = {{grp_fu_1626_p3}, {6'd0}};

assign shl_ln_fu_1453_p3 = {{grp_fu_1617_p3}, {6'd0}};

assign tmp_5_fu_1482_p3 = add_ln18_1_fu_1464_p2[32'd47];

assign tmp_6_fu_1545_p3 = add_ln19_fu_1539_p2[32'd48];

assign tmp_7_fu_1557_p3 = add_ln19_fu_1539_p2[32'd47];

assign tmp_fu_1470_p3 = add_ln18_1_fu_1464_p2[32'd48];

assign xor_ln18_1_fu_1502_p2 = (tmp_fu_1470_p3 ^ tmp_5_fu_1482_p3);

assign xor_ln18_fu_1490_p2 = (tmp_fu_1470_p3 ^ 1'd1);

assign xor_ln19_1_fu_1577_p2 = (tmp_7_fu_1557_p3 ^ tmp_6_fu_1545_p3);

assign xor_ln19_fu_1565_p2 = (tmp_6_fu_1545_p3 ^ 1'd1);

assign zext_ln82_fu_802_p1 = ap_sig_allocacmp_t_1;

endmodule //covariance_estimation_covariance_estimation_Pipeline_INNER_K
