// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module covariance_estimation_covariance_estimation_Pipeline_WRITE_ROW_WRITE_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        empty_25,
        R_buf_re_address0,
        R_buf_re_ce0,
        R_buf_re_q0,
        R_buf_re_1_address0,
        R_buf_re_1_ce0,
        R_buf_re_1_q0,
        R_buf_re_2_address0,
        R_buf_re_2_ce0,
        R_buf_re_2_q0,
        R_buf_re_3_address0,
        R_buf_re_3_ce0,
        R_buf_re_3_q0,
        R_buf_re_4_address0,
        R_buf_re_4_ce0,
        R_buf_re_4_q0,
        R_buf_re_5_address0,
        R_buf_re_5_ce0,
        R_buf_re_5_q0,
        R_buf_re_6_address0,
        R_buf_re_6_ce0,
        R_buf_re_6_q0,
        R_buf_re_7_address0,
        R_buf_re_7_ce0,
        R_buf_re_7_q0,
        R_buf_re_8_address0,
        R_buf_re_8_ce0,
        R_buf_re_8_q0,
        R_buf_re_9_address0,
        R_buf_re_9_ce0,
        R_buf_re_9_q0,
        R_buf_re_10_address0,
        R_buf_re_10_ce0,
        R_buf_re_10_q0,
        R_buf_re_11_address0,
        R_buf_re_11_ce0,
        R_buf_re_11_q0,
        R_buf_re_12_address0,
        R_buf_re_12_ce0,
        R_buf_re_12_q0,
        R_buf_re_13_address0,
        R_buf_re_13_ce0,
        R_buf_re_13_q0,
        R_buf_re_14_address0,
        R_buf_re_14_ce0,
        R_buf_re_14_q0,
        R_buf_re_15_address0,
        R_buf_re_15_ce0,
        R_buf_re_15_q0,
        R_buf_re_16_address0,
        R_buf_re_16_ce0,
        R_buf_re_16_q0,
        R_buf_re_17_address0,
        R_buf_re_17_ce0,
        R_buf_re_17_q0,
        R_buf_re_18_address0,
        R_buf_re_18_ce0,
        R_buf_re_18_q0,
        R_buf_re_19_address0,
        R_buf_re_19_ce0,
        R_buf_re_19_q0,
        R_buf_re_20_address0,
        R_buf_re_20_ce0,
        R_buf_re_20_q0,
        R_buf_im_address0,
        R_buf_im_ce0,
        R_buf_im_q0,
        R_buf_im_1_address0,
        R_buf_im_1_ce0,
        R_buf_im_1_q0,
        R_buf_im_2_address0,
        R_buf_im_2_ce0,
        R_buf_im_2_q0,
        R_buf_im_3_address0,
        R_buf_im_3_ce0,
        R_buf_im_3_q0,
        R_buf_im_4_address0,
        R_buf_im_4_ce0,
        R_buf_im_4_q0,
        R_buf_im_5_address0,
        R_buf_im_5_ce0,
        R_buf_im_5_q0,
        R_buf_im_6_address0,
        R_buf_im_6_ce0,
        R_buf_im_6_q0,
        R_buf_im_7_address0,
        R_buf_im_7_ce0,
        R_buf_im_7_q0,
        R_buf_im_8_address0,
        R_buf_im_8_ce0,
        R_buf_im_8_q0,
        R_buf_im_9_address0,
        R_buf_im_9_ce0,
        R_buf_im_9_q0,
        R_buf_im_10_address0,
        R_buf_im_10_ce0,
        R_buf_im_10_q0,
        R_buf_im_11_address0,
        R_buf_im_11_ce0,
        R_buf_im_11_q0,
        R_buf_im_12_address0,
        R_buf_im_12_ce0,
        R_buf_im_12_q0,
        R_buf_im_13_address0,
        R_buf_im_13_ce0,
        R_buf_im_13_q0,
        R_buf_im_14_address0,
        R_buf_im_14_ce0,
        R_buf_im_14_q0,
        R_buf_im_15_address0,
        R_buf_im_15_ce0,
        R_buf_im_15_q0,
        R_buf_im_16_address0,
        R_buf_im_16_ce0,
        R_buf_im_16_q0,
        R_buf_im_17_address0,
        R_buf_im_17_ce0,
        R_buf_im_17_q0,
        R_buf_im_18_address0,
        R_buf_im_18_ce0,
        R_buf_im_18_q0,
        R_buf_im_19_address0,
        R_buf_im_19_ce0,
        R_buf_im_19_q0,
        R_buf_im_20_address0,
        R_buf_im_20_ce0,
        R_buf_im_20_q0,
        R,
        zext_ln109_1,
        select_ln109,
        empty,
        zext_ln109_2
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [63:0] m_axi_gmem_0_WDATA;
output  [7:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [63:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [2:0] empty_25;
output  [4:0] R_buf_re_address0;
output   R_buf_re_ce0;
input  [31:0] R_buf_re_q0;
output  [4:0] R_buf_re_1_address0;
output   R_buf_re_1_ce0;
input  [31:0] R_buf_re_1_q0;
output  [4:0] R_buf_re_2_address0;
output   R_buf_re_2_ce0;
input  [31:0] R_buf_re_2_q0;
output  [4:0] R_buf_re_3_address0;
output   R_buf_re_3_ce0;
input  [31:0] R_buf_re_3_q0;
output  [4:0] R_buf_re_4_address0;
output   R_buf_re_4_ce0;
input  [31:0] R_buf_re_4_q0;
output  [4:0] R_buf_re_5_address0;
output   R_buf_re_5_ce0;
input  [31:0] R_buf_re_5_q0;
output  [4:0] R_buf_re_6_address0;
output   R_buf_re_6_ce0;
input  [31:0] R_buf_re_6_q0;
output  [4:0] R_buf_re_7_address0;
output   R_buf_re_7_ce0;
input  [31:0] R_buf_re_7_q0;
output  [4:0] R_buf_re_8_address0;
output   R_buf_re_8_ce0;
input  [31:0] R_buf_re_8_q0;
output  [4:0] R_buf_re_9_address0;
output   R_buf_re_9_ce0;
input  [31:0] R_buf_re_9_q0;
output  [4:0] R_buf_re_10_address0;
output   R_buf_re_10_ce0;
input  [31:0] R_buf_re_10_q0;
output  [4:0] R_buf_re_11_address0;
output   R_buf_re_11_ce0;
input  [31:0] R_buf_re_11_q0;
output  [4:0] R_buf_re_12_address0;
output   R_buf_re_12_ce0;
input  [31:0] R_buf_re_12_q0;
output  [4:0] R_buf_re_13_address0;
output   R_buf_re_13_ce0;
input  [31:0] R_buf_re_13_q0;
output  [4:0] R_buf_re_14_address0;
output   R_buf_re_14_ce0;
input  [31:0] R_buf_re_14_q0;
output  [4:0] R_buf_re_15_address0;
output   R_buf_re_15_ce0;
input  [31:0] R_buf_re_15_q0;
output  [4:0] R_buf_re_16_address0;
output   R_buf_re_16_ce0;
input  [31:0] R_buf_re_16_q0;
output  [4:0] R_buf_re_17_address0;
output   R_buf_re_17_ce0;
input  [31:0] R_buf_re_17_q0;
output  [4:0] R_buf_re_18_address0;
output   R_buf_re_18_ce0;
input  [31:0] R_buf_re_18_q0;
output  [4:0] R_buf_re_19_address0;
output   R_buf_re_19_ce0;
input  [31:0] R_buf_re_19_q0;
output  [4:0] R_buf_re_20_address0;
output   R_buf_re_20_ce0;
input  [31:0] R_buf_re_20_q0;
output  [4:0] R_buf_im_address0;
output   R_buf_im_ce0;
input  [31:0] R_buf_im_q0;
output  [4:0] R_buf_im_1_address0;
output   R_buf_im_1_ce0;
input  [31:0] R_buf_im_1_q0;
output  [4:0] R_buf_im_2_address0;
output   R_buf_im_2_ce0;
input  [31:0] R_buf_im_2_q0;
output  [4:0] R_buf_im_3_address0;
output   R_buf_im_3_ce0;
input  [31:0] R_buf_im_3_q0;
output  [4:0] R_buf_im_4_address0;
output   R_buf_im_4_ce0;
input  [31:0] R_buf_im_4_q0;
output  [4:0] R_buf_im_5_address0;
output   R_buf_im_5_ce0;
input  [31:0] R_buf_im_5_q0;
output  [4:0] R_buf_im_6_address0;
output   R_buf_im_6_ce0;
input  [31:0] R_buf_im_6_q0;
output  [4:0] R_buf_im_7_address0;
output   R_buf_im_7_ce0;
input  [31:0] R_buf_im_7_q0;
output  [4:0] R_buf_im_8_address0;
output   R_buf_im_8_ce0;
input  [31:0] R_buf_im_8_q0;
output  [4:0] R_buf_im_9_address0;
output   R_buf_im_9_ce0;
input  [31:0] R_buf_im_9_q0;
output  [4:0] R_buf_im_10_address0;
output   R_buf_im_10_ce0;
input  [31:0] R_buf_im_10_q0;
output  [4:0] R_buf_im_11_address0;
output   R_buf_im_11_ce0;
input  [31:0] R_buf_im_11_q0;
output  [4:0] R_buf_im_12_address0;
output   R_buf_im_12_ce0;
input  [31:0] R_buf_im_12_q0;
output  [4:0] R_buf_im_13_address0;
output   R_buf_im_13_ce0;
input  [31:0] R_buf_im_13_q0;
output  [4:0] R_buf_im_14_address0;
output   R_buf_im_14_ce0;
input  [31:0] R_buf_im_14_q0;
output  [4:0] R_buf_im_15_address0;
output   R_buf_im_15_ce0;
input  [31:0] R_buf_im_15_q0;
output  [4:0] R_buf_im_16_address0;
output   R_buf_im_16_ce0;
input  [31:0] R_buf_im_16_q0;
output  [4:0] R_buf_im_17_address0;
output   R_buf_im_17_ce0;
input  [31:0] R_buf_im_17_q0;
output  [4:0] R_buf_im_18_address0;
output   R_buf_im_18_ce0;
input  [31:0] R_buf_im_18_q0;
output  [4:0] R_buf_im_19_address0;
output   R_buf_im_19_ce0;
input  [31:0] R_buf_im_19_q0;
output  [4:0] R_buf_im_20_address0;
output   R_buf_im_20_ce0;
input  [31:0] R_buf_im_20_q0;
input  [63:0] R;
input  [5:0] zext_ln109_1;
input  [1:0] select_ln109;
input  [7:0] empty;
input  [6:0] zext_ln109_2;

reg ap_idle;
reg m_axi_gmem_0_AWVALID;
reg m_axi_gmem_0_WVALID;
reg[63:0] m_axi_gmem_0_WDATA;
reg[7:0] m_axi_gmem_0_WSTRB;
reg m_axi_gmem_0_BREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln105_reg_1470;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_B;
wire    ap_block_pp0_stage0_grp4;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
reg    ap_block_pp0_stage0_subdone;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage1_grp2;
reg   [0:0] icmp_ln109_reg_1466;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_state5_io_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] zext_ln109_2_cast_fu_840_p1;
reg   [7:0] zext_ln109_2_cast_reg_1449;
wire   [63:0] select_ln109_cast_fu_844_p1;
reg   [63:0] select_ln109_cast_reg_1455;
wire   [119:0] zext_ln109_1_cast_fu_848_p1;
reg   [119:0] zext_ln109_1_cast_reg_1461;
wire   [0:0] icmp_ln109_fu_852_p2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln105_fu_882_p2;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter1_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter2_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter3_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter4_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter5_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter6_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter7_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter8_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter9_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter10_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter11_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter12_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter13_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter14_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter15_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter16_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter17_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter18_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter19_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter20_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter21_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter22_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter23_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter24_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter25_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter26_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter27_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter28_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter29_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter30_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter31_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter32_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter33_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter34_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter35_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter36_reg;
reg   [0:0] icmp_ln105_reg_1470_pp0_iter37_reg;
wire   [4:0] select_ln105_fu_900_p3;
reg   [4:0] select_ln105_reg_1474;
wire   [4:0] select_ln105_1_fu_914_p3;
reg   [4:0] select_ln105_1_reg_1479;
wire   [12:0] mul_ln109_fu_1168_p2;
reg   [12:0] mul_ln109_reg_1696;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [31:0] R_buf_re_load_reg_1701;
reg   [31:0] R_buf_re_1_load_reg_1706;
reg   [31:0] R_buf_re_2_load_reg_1711;
reg   [31:0] R_buf_re_3_load_reg_1716;
reg   [31:0] R_buf_re_4_load_reg_1721;
reg   [31:0] R_buf_re_5_load_reg_1726;
reg   [31:0] R_buf_re_6_load_reg_1731;
reg   [31:0] R_buf_re_7_load_reg_1736;
reg   [31:0] R_buf_re_8_load_reg_1741;
reg   [31:0] R_buf_re_9_load_reg_1746;
reg   [31:0] R_buf_re_10_load_reg_1751;
reg   [31:0] R_buf_re_11_load_reg_1756;
reg   [31:0] R_buf_re_12_load_reg_1761;
reg   [31:0] R_buf_re_13_load_reg_1766;
reg   [31:0] R_buf_re_14_load_reg_1771;
reg   [31:0] R_buf_re_15_load_reg_1776;
reg   [31:0] R_buf_re_16_load_reg_1781;
reg   [31:0] R_buf_re_17_load_reg_1786;
reg   [31:0] R_buf_re_18_load_reg_1791;
reg   [31:0] R_buf_re_19_load_reg_1796;
reg   [31:0] R_buf_re_20_load_reg_1801;
reg   [31:0] R_buf_im_load_reg_1806;
reg   [31:0] R_buf_im_1_load_reg_1811;
reg   [31:0] R_buf_im_2_load_reg_1816;
reg   [31:0] R_buf_im_3_load_reg_1821;
reg   [31:0] R_buf_im_4_load_reg_1826;
reg   [31:0] R_buf_im_5_load_reg_1831;
reg   [31:0] R_buf_im_6_load_reg_1836;
reg   [31:0] R_buf_im_7_load_reg_1841;
reg   [31:0] R_buf_im_8_load_reg_1846;
reg   [31:0] R_buf_im_9_load_reg_1851;
reg   [31:0] R_buf_im_10_load_reg_1856;
reg   [31:0] R_buf_im_11_load_reg_1861;
reg   [31:0] R_buf_im_12_load_reg_1866;
reg   [31:0] R_buf_im_13_load_reg_1871;
reg   [31:0] R_buf_im_14_load_reg_1876;
reg   [31:0] R_buf_im_15_load_reg_1881;
reg   [31:0] R_buf_im_16_load_reg_1886;
reg   [31:0] R_buf_im_17_load_reg_1891;
reg   [31:0] R_buf_im_18_load_reg_1896;
reg   [31:0] R_buf_im_19_load_reg_1901;
reg   [31:0] R_buf_im_20_load_reg_1906;
wire   [31:0] tmp_fu_1199_p45;
reg   [31:0] tmp_reg_1911;
wire   [31:0] tmp_2_fu_1269_p45;
reg   [31:0] tmp_2_reg_1916;
reg   [55:0] tmp_s_reg_1927;
reg    ap_block_pp0_stage1_11001_grp2;
wire   [63:0] zext_ln107_1_fu_922_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln109_fu_1349_p1;
wire   [63:0] trunc_ln109_fu_1382_p1;
wire    ap_block_pp0_stage1_01001_grp2;
wire   [63:0] zext_ln109_4_fu_1404_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp4;
reg   [4:0] j_fu_228;
wire   [4:0] add_ln107_fu_1136_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_232;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [8:0] indvar_flatten6_fu_236;
wire   [8:0] add_ln105_fu_876_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    R_buf_re_ce0_local;
reg    R_buf_re_1_ce0_local;
reg    R_buf_re_2_ce0_local;
reg    R_buf_re_3_ce0_local;
reg    R_buf_re_4_ce0_local;
reg    R_buf_re_5_ce0_local;
reg    R_buf_re_6_ce0_local;
reg    R_buf_re_7_ce0_local;
reg    R_buf_re_8_ce0_local;
reg    R_buf_re_9_ce0_local;
reg    R_buf_re_10_ce0_local;
reg    R_buf_re_11_ce0_local;
reg    R_buf_re_12_ce0_local;
reg    R_buf_re_13_ce0_local;
reg    R_buf_re_14_ce0_local;
reg    R_buf_re_15_ce0_local;
reg    R_buf_re_16_ce0_local;
reg    R_buf_re_17_ce0_local;
reg    R_buf_re_18_ce0_local;
reg    R_buf_re_19_ce0_local;
reg    R_buf_re_20_ce0_local;
reg    R_buf_im_ce0_local;
reg    R_buf_im_1_ce0_local;
reg    R_buf_im_2_ce0_local;
reg    R_buf_im_3_ce0_local;
reg    R_buf_im_4_ce0_local;
reg    R_buf_im_5_ce0_local;
reg    R_buf_im_6_ce0_local;
reg    R_buf_im_7_ce0_local;
reg    R_buf_im_8_ce0_local;
reg    R_buf_im_9_ce0_local;
reg    R_buf_im_10_ce0_local;
reg    R_buf_im_11_ce0_local;
reg    R_buf_im_12_ce0_local;
reg    R_buf_im_13_ce0_local;
reg    R_buf_im_14_ce0_local;
reg    R_buf_im_15_ce0_local;
reg    R_buf_im_16_ce0_local;
reg    R_buf_im_17_ce0_local;
reg    R_buf_im_18_ce0_local;
reg    R_buf_im_19_ce0_local;
reg    R_buf_im_20_ce0_local;
wire    ap_block_pp0_stage0_grp0;
wire   [0:0] icmp_ln107_fu_894_p2;
wire   [4:0] add_ln105_1_fu_908_p2;
wire    ap_block_pp0_stage1_grp0;
wire   [4:0] mul_ln109_fu_1168_p0;
wire   [8:0] mul_ln109_fu_1168_p1;
wire   [7:0] shl_ln109_3_fu_1177_p3;
wire   [63:0] zext_ln109_fu_1184_p1;
wire   [63:0] add_ln109_fu_1188_p2;
wire   [63:0] zext_ln107_fu_1174_p1;
wire   [31:0] tmp_fu_1199_p43;
wire   [31:0] tmp_2_fu_1269_p43;
wire   [63:0] add_ln109_1_fu_1193_p2;
wire   [60:0] trunc_ln109_4_fu_1339_p4;
wire   [63:0] tmp_3_fu_1367_p3;
wire   [119:0] zext_ln109_3_fu_1373_p1;
wire   [119:0] shl_ln109_fu_1377_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg    ap_condition_exit_pp0_iter38_stage0;
reg    ap_idle_pp0_0to37;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] mul_ln109_fu_1168_p00;
wire   [4:0] tmp_fu_1199_p1;
wire   [4:0] tmp_fu_1199_p3;
wire   [4:0] tmp_fu_1199_p5;
wire   [4:0] tmp_fu_1199_p7;
wire   [4:0] tmp_fu_1199_p9;
wire   [4:0] tmp_fu_1199_p11;
wire   [4:0] tmp_fu_1199_p13;
wire   [4:0] tmp_fu_1199_p15;
wire   [4:0] tmp_fu_1199_p17;
wire   [4:0] tmp_fu_1199_p19;
wire   [4:0] tmp_fu_1199_p21;
wire   [4:0] tmp_fu_1199_p23;
wire   [4:0] tmp_fu_1199_p25;
wire   [4:0] tmp_fu_1199_p27;
wire   [4:0] tmp_fu_1199_p29;
wire   [4:0] tmp_fu_1199_p31;
wire  signed [4:0] tmp_fu_1199_p33;
wire  signed [4:0] tmp_fu_1199_p35;
wire  signed [4:0] tmp_fu_1199_p37;
wire  signed [4:0] tmp_fu_1199_p39;
wire  signed [4:0] tmp_fu_1199_p41;
wire   [4:0] tmp_2_fu_1269_p1;
wire   [4:0] tmp_2_fu_1269_p3;
wire   [4:0] tmp_2_fu_1269_p5;
wire   [4:0] tmp_2_fu_1269_p7;
wire   [4:0] tmp_2_fu_1269_p9;
wire   [4:0] tmp_2_fu_1269_p11;
wire   [4:0] tmp_2_fu_1269_p13;
wire   [4:0] tmp_2_fu_1269_p15;
wire   [4:0] tmp_2_fu_1269_p17;
wire   [4:0] tmp_2_fu_1269_p19;
wire   [4:0] tmp_2_fu_1269_p21;
wire   [4:0] tmp_2_fu_1269_p23;
wire   [4:0] tmp_2_fu_1269_p25;
wire   [4:0] tmp_2_fu_1269_p27;
wire   [4:0] tmp_2_fu_1269_p29;
wire   [4:0] tmp_2_fu_1269_p31;
wire  signed [4:0] tmp_2_fu_1269_p33;
wire  signed [4:0] tmp_2_fu_1269_p35;
wire  signed [4:0] tmp_2_fu_1269_p37;
wire  signed [4:0] tmp_2_fu_1269_p39;
wire  signed [4:0] tmp_2_fu_1269_p41;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 j_fu_228 = 5'd0;
#0 i_fu_232 = 5'd0;
#0 indvar_flatten6_fu_236 = 9'd0;
#0 ap_done_reg = 1'b0;
end

covariance_estimation_mul_5ns_9ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 13 ))
mul_5ns_9ns_13_1_1_U102(
    .din0(mul_ln109_fu_1168_p0),
    .din1(mul_ln109_fu_1168_p1),
    .dout(mul_ln109_fu_1168_p2)
);

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U103(
    .din0(R_buf_re_load_reg_1701),
    .din1(R_buf_re_1_load_reg_1706),
    .din2(R_buf_re_2_load_reg_1711),
    .din3(R_buf_re_3_load_reg_1716),
    .din4(R_buf_re_4_load_reg_1721),
    .din5(R_buf_re_5_load_reg_1726),
    .din6(R_buf_re_6_load_reg_1731),
    .din7(R_buf_re_7_load_reg_1736),
    .din8(R_buf_re_8_load_reg_1741),
    .din9(R_buf_re_9_load_reg_1746),
    .din10(R_buf_re_10_load_reg_1751),
    .din11(R_buf_re_11_load_reg_1756),
    .din12(R_buf_re_12_load_reg_1761),
    .din13(R_buf_re_13_load_reg_1766),
    .din14(R_buf_re_14_load_reg_1771),
    .din15(R_buf_re_15_load_reg_1776),
    .din16(R_buf_re_16_load_reg_1781),
    .din17(R_buf_re_17_load_reg_1786),
    .din18(R_buf_re_18_load_reg_1791),
    .din19(R_buf_re_19_load_reg_1796),
    .din20(R_buf_re_20_load_reg_1801),
    .def(tmp_fu_1199_p43),
    .sel(select_ln105_1_reg_1479),
    .dout(tmp_fu_1199_p45)
);

(* dissolve_hierarchy = "yes" *) covariance_estimation_sparsemux_43_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_43_5_32_1_1_U104(
    .din0(R_buf_im_load_reg_1806),
    .din1(R_buf_im_1_load_reg_1811),
    .din2(R_buf_im_2_load_reg_1816),
    .din3(R_buf_im_3_load_reg_1821),
    .din4(R_buf_im_4_load_reg_1826),
    .din5(R_buf_im_5_load_reg_1831),
    .din6(R_buf_im_6_load_reg_1836),
    .din7(R_buf_im_7_load_reg_1841),
    .din8(R_buf_im_8_load_reg_1846),
    .din9(R_buf_im_9_load_reg_1851),
    .din10(R_buf_im_10_load_reg_1856),
    .din11(R_buf_im_11_load_reg_1861),
    .din12(R_buf_im_12_load_reg_1866),
    .din13(R_buf_im_13_load_reg_1871),
    .din14(R_buf_im_14_load_reg_1876),
    .din15(R_buf_im_15_load_reg_1881),
    .din16(R_buf_im_16_load_reg_1886),
    .din17(R_buf_im_17_load_reg_1891),
    .din18(R_buf_im_18_load_reg_1896),
    .din19(R_buf_im_19_load_reg_1901),
    .din20(R_buf_im_20_load_reg_1906),
    .def(tmp_2_fu_1269_p43),
    .sel(select_ln105_1_reg_1479),
    .dout(tmp_2_fu_1269_p45)
);

covariance_estimation_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
            ap_enable_reg_pp0_iter39 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_232 <= select_ln105_1_fu_914_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_232 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_236 <= add_ln105_fu_876_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_236 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_228 <= add_ln107_fu_1136_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_228 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        R_buf_im_10_load_reg_1856 <= R_buf_im_10_q0;
        R_buf_im_11_load_reg_1861 <= R_buf_im_11_q0;
        R_buf_im_12_load_reg_1866 <= R_buf_im_12_q0;
        R_buf_im_13_load_reg_1871 <= R_buf_im_13_q0;
        R_buf_im_14_load_reg_1876 <= R_buf_im_14_q0;
        R_buf_im_15_load_reg_1881 <= R_buf_im_15_q0;
        R_buf_im_16_load_reg_1886 <= R_buf_im_16_q0;
        R_buf_im_17_load_reg_1891 <= R_buf_im_17_q0;
        R_buf_im_18_load_reg_1896 <= R_buf_im_18_q0;
        R_buf_im_19_load_reg_1901 <= R_buf_im_19_q0;
        R_buf_im_1_load_reg_1811 <= R_buf_im_1_q0;
        R_buf_im_20_load_reg_1906 <= R_buf_im_20_q0;
        R_buf_im_2_load_reg_1816 <= R_buf_im_2_q0;
        R_buf_im_3_load_reg_1821 <= R_buf_im_3_q0;
        R_buf_im_4_load_reg_1826 <= R_buf_im_4_q0;
        R_buf_im_5_load_reg_1831 <= R_buf_im_5_q0;
        R_buf_im_6_load_reg_1836 <= R_buf_im_6_q0;
        R_buf_im_7_load_reg_1841 <= R_buf_im_7_q0;
        R_buf_im_8_load_reg_1846 <= R_buf_im_8_q0;
        R_buf_im_9_load_reg_1851 <= R_buf_im_9_q0;
        R_buf_im_load_reg_1806 <= R_buf_im_q0;
        R_buf_re_10_load_reg_1751 <= R_buf_re_10_q0;
        R_buf_re_11_load_reg_1756 <= R_buf_re_11_q0;
        R_buf_re_12_load_reg_1761 <= R_buf_re_12_q0;
        R_buf_re_13_load_reg_1766 <= R_buf_re_13_q0;
        R_buf_re_14_load_reg_1771 <= R_buf_re_14_q0;
        R_buf_re_15_load_reg_1776 <= R_buf_re_15_q0;
        R_buf_re_16_load_reg_1781 <= R_buf_re_16_q0;
        R_buf_re_17_load_reg_1786 <= R_buf_re_17_q0;
        R_buf_re_18_load_reg_1791 <= R_buf_re_18_q0;
        R_buf_re_19_load_reg_1796 <= R_buf_re_19_q0;
        R_buf_re_1_load_reg_1706 <= R_buf_re_1_q0;
        R_buf_re_20_load_reg_1801 <= R_buf_re_20_q0;
        R_buf_re_2_load_reg_1711 <= R_buf_re_2_q0;
        R_buf_re_3_load_reg_1716 <= R_buf_re_3_q0;
        R_buf_re_4_load_reg_1721 <= R_buf_re_4_q0;
        R_buf_re_5_load_reg_1726 <= R_buf_re_5_q0;
        R_buf_re_6_load_reg_1731 <= R_buf_re_6_q0;
        R_buf_re_7_load_reg_1736 <= R_buf_re_7_q0;
        R_buf_re_8_load_reg_1741 <= R_buf_re_8_q0;
        R_buf_re_9_load_reg_1746 <= R_buf_re_9_q0;
        R_buf_re_load_reg_1701 <= R_buf_re_q0;
        mul_ln109_reg_1696 <= mul_ln109_fu_1168_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln105_reg_1470 <= icmp_ln105_fu_882_p2;
        icmp_ln105_reg_1470_pp0_iter10_reg <= icmp_ln105_reg_1470_pp0_iter9_reg;
        icmp_ln105_reg_1470_pp0_iter11_reg <= icmp_ln105_reg_1470_pp0_iter10_reg;
        icmp_ln105_reg_1470_pp0_iter12_reg <= icmp_ln105_reg_1470_pp0_iter11_reg;
        icmp_ln105_reg_1470_pp0_iter13_reg <= icmp_ln105_reg_1470_pp0_iter12_reg;
        icmp_ln105_reg_1470_pp0_iter14_reg <= icmp_ln105_reg_1470_pp0_iter13_reg;
        icmp_ln105_reg_1470_pp0_iter15_reg <= icmp_ln105_reg_1470_pp0_iter14_reg;
        icmp_ln105_reg_1470_pp0_iter16_reg <= icmp_ln105_reg_1470_pp0_iter15_reg;
        icmp_ln105_reg_1470_pp0_iter17_reg <= icmp_ln105_reg_1470_pp0_iter16_reg;
        icmp_ln105_reg_1470_pp0_iter18_reg <= icmp_ln105_reg_1470_pp0_iter17_reg;
        icmp_ln105_reg_1470_pp0_iter19_reg <= icmp_ln105_reg_1470_pp0_iter18_reg;
        icmp_ln105_reg_1470_pp0_iter1_reg <= icmp_ln105_reg_1470;
        icmp_ln105_reg_1470_pp0_iter20_reg <= icmp_ln105_reg_1470_pp0_iter19_reg;
        icmp_ln105_reg_1470_pp0_iter21_reg <= icmp_ln105_reg_1470_pp0_iter20_reg;
        icmp_ln105_reg_1470_pp0_iter22_reg <= icmp_ln105_reg_1470_pp0_iter21_reg;
        icmp_ln105_reg_1470_pp0_iter23_reg <= icmp_ln105_reg_1470_pp0_iter22_reg;
        icmp_ln105_reg_1470_pp0_iter24_reg <= icmp_ln105_reg_1470_pp0_iter23_reg;
        icmp_ln105_reg_1470_pp0_iter25_reg <= icmp_ln105_reg_1470_pp0_iter24_reg;
        icmp_ln105_reg_1470_pp0_iter26_reg <= icmp_ln105_reg_1470_pp0_iter25_reg;
        icmp_ln105_reg_1470_pp0_iter27_reg <= icmp_ln105_reg_1470_pp0_iter26_reg;
        icmp_ln105_reg_1470_pp0_iter28_reg <= icmp_ln105_reg_1470_pp0_iter27_reg;
        icmp_ln105_reg_1470_pp0_iter29_reg <= icmp_ln105_reg_1470_pp0_iter28_reg;
        icmp_ln105_reg_1470_pp0_iter2_reg <= icmp_ln105_reg_1470_pp0_iter1_reg;
        icmp_ln105_reg_1470_pp0_iter30_reg <= icmp_ln105_reg_1470_pp0_iter29_reg;
        icmp_ln105_reg_1470_pp0_iter31_reg <= icmp_ln105_reg_1470_pp0_iter30_reg;
        icmp_ln105_reg_1470_pp0_iter32_reg <= icmp_ln105_reg_1470_pp0_iter31_reg;
        icmp_ln105_reg_1470_pp0_iter33_reg <= icmp_ln105_reg_1470_pp0_iter32_reg;
        icmp_ln105_reg_1470_pp0_iter34_reg <= icmp_ln105_reg_1470_pp0_iter33_reg;
        icmp_ln105_reg_1470_pp0_iter35_reg <= icmp_ln105_reg_1470_pp0_iter34_reg;
        icmp_ln105_reg_1470_pp0_iter36_reg <= icmp_ln105_reg_1470_pp0_iter35_reg;
        icmp_ln105_reg_1470_pp0_iter37_reg <= icmp_ln105_reg_1470_pp0_iter36_reg;
        icmp_ln105_reg_1470_pp0_iter3_reg <= icmp_ln105_reg_1470_pp0_iter2_reg;
        icmp_ln105_reg_1470_pp0_iter4_reg <= icmp_ln105_reg_1470_pp0_iter3_reg;
        icmp_ln105_reg_1470_pp0_iter5_reg <= icmp_ln105_reg_1470_pp0_iter4_reg;
        icmp_ln105_reg_1470_pp0_iter6_reg <= icmp_ln105_reg_1470_pp0_iter5_reg;
        icmp_ln105_reg_1470_pp0_iter7_reg <= icmp_ln105_reg_1470_pp0_iter6_reg;
        icmp_ln105_reg_1470_pp0_iter8_reg <= icmp_ln105_reg_1470_pp0_iter7_reg;
        icmp_ln105_reg_1470_pp0_iter9_reg <= icmp_ln105_reg_1470_pp0_iter8_reg;
        icmp_ln109_reg_1466 <= icmp_ln109_fu_852_p2;
        select_ln105_1_reg_1479 <= select_ln105_1_fu_914_p3;
        select_ln105_reg_1474 <= select_ln105_fu_900_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln109_cast_reg_1455[1 : 0] <= select_ln109_cast_fu_844_p1[1 : 0];
        zext_ln109_2_cast_reg_1449[6 : 0] <= zext_ln109_2_cast_fu_840_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_1916 <= tmp_2_fu_1269_p45;
        tmp_reg_1911 <= tmp_fu_1199_p45;
        zext_ln109_1_cast_reg_1461[5 : 0] <= zext_ln109_1_cast_fu_848_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_s_reg_1927 <= {{shl_ln109_fu_1377_p2[119:64]}};
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_10_ce0_local = 1'b1;
    end else begin
        R_buf_im_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_11_ce0_local = 1'b1;
    end else begin
        R_buf_im_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_12_ce0_local = 1'b1;
    end else begin
        R_buf_im_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_13_ce0_local = 1'b1;
    end else begin
        R_buf_im_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_14_ce0_local = 1'b1;
    end else begin
        R_buf_im_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_15_ce0_local = 1'b1;
    end else begin
        R_buf_im_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_16_ce0_local = 1'b1;
    end else begin
        R_buf_im_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_17_ce0_local = 1'b1;
    end else begin
        R_buf_im_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_18_ce0_local = 1'b1;
    end else begin
        R_buf_im_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_19_ce0_local = 1'b1;
    end else begin
        R_buf_im_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_1_ce0_local = 1'b1;
    end else begin
        R_buf_im_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_20_ce0_local = 1'b1;
    end else begin
        R_buf_im_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_2_ce0_local = 1'b1;
    end else begin
        R_buf_im_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_3_ce0_local = 1'b1;
    end else begin
        R_buf_im_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_4_ce0_local = 1'b1;
    end else begin
        R_buf_im_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_5_ce0_local = 1'b1;
    end else begin
        R_buf_im_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_6_ce0_local = 1'b1;
    end else begin
        R_buf_im_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_7_ce0_local = 1'b1;
    end else begin
        R_buf_im_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_8_ce0_local = 1'b1;
    end else begin
        R_buf_im_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_9_ce0_local = 1'b1;
    end else begin
        R_buf_im_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_im_ce0_local = 1'b1;
    end else begin
        R_buf_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_10_ce0_local = 1'b1;
    end else begin
        R_buf_re_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_11_ce0_local = 1'b1;
    end else begin
        R_buf_re_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_12_ce0_local = 1'b1;
    end else begin
        R_buf_re_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_13_ce0_local = 1'b1;
    end else begin
        R_buf_re_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_14_ce0_local = 1'b1;
    end else begin
        R_buf_re_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_15_ce0_local = 1'b1;
    end else begin
        R_buf_re_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_16_ce0_local = 1'b1;
    end else begin
        R_buf_re_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_17_ce0_local = 1'b1;
    end else begin
        R_buf_re_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_18_ce0_local = 1'b1;
    end else begin
        R_buf_re_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_19_ce0_local = 1'b1;
    end else begin
        R_buf_re_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_1_ce0_local = 1'b1;
    end else begin
        R_buf_re_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_20_ce0_local = 1'b1;
    end else begin
        R_buf_re_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_2_ce0_local = 1'b1;
    end else begin
        R_buf_re_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_3_ce0_local = 1'b1;
    end else begin
        R_buf_re_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_4_ce0_local = 1'b1;
    end else begin
        R_buf_re_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_5_ce0_local = 1'b1;
    end else begin
        R_buf_re_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_6_ce0_local = 1'b1;
    end else begin
        R_buf_re_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_7_ce0_local = 1'b1;
    end else begin
        R_buf_re_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_8_ce0_local = 1'b1;
    end else begin
        R_buf_re_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_9_ce0_local = 1'b1;
    end else begin
        R_buf_re_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_buf_re_ce0_local = 1'b1;
    end else begin
        R_buf_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_reg_1470 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_reg_1470_pp0_iter37_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter38 == 1'b1))) begin
        ap_condition_exit_pp0_iter38_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter38_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) 
    & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) 
    & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_0to37 = 1'b1;
    end else begin
        ap_idle_pp0_0to37 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_232;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_236;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_228;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_0_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage0_grp4) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        gmem_blk_n_B = m_axi_gmem_0_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln109_reg_1466 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        gmem_blk_n_W = m_axi_gmem_0_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        m_axi_gmem_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_1466 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_0_WDATA = zext_ln109_4_fu_1404_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem_0_WDATA = trunc_ln109_fu_1382_p1;
    end else begin
        m_axi_gmem_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_1466 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_0_WSTRB = zext_ln109_2_cast_reg_1449;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem_0_WSTRB = empty;
    end else begin
        m_axi_gmem_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln109_reg_1466 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_axi_gmem_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter38_stage0) & (ap_idle_pp0_0to37 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_buf_im_10_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_10_ce0 = R_buf_im_10_ce0_local;

assign R_buf_im_11_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_11_ce0 = R_buf_im_11_ce0_local;

assign R_buf_im_12_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_12_ce0 = R_buf_im_12_ce0_local;

assign R_buf_im_13_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_13_ce0 = R_buf_im_13_ce0_local;

assign R_buf_im_14_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_14_ce0 = R_buf_im_14_ce0_local;

assign R_buf_im_15_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_15_ce0 = R_buf_im_15_ce0_local;

assign R_buf_im_16_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_16_ce0 = R_buf_im_16_ce0_local;

assign R_buf_im_17_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_17_ce0 = R_buf_im_17_ce0_local;

assign R_buf_im_18_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_18_ce0 = R_buf_im_18_ce0_local;

assign R_buf_im_19_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_19_ce0 = R_buf_im_19_ce0_local;

assign R_buf_im_1_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_1_ce0 = R_buf_im_1_ce0_local;

assign R_buf_im_20_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_20_ce0 = R_buf_im_20_ce0_local;

assign R_buf_im_2_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_2_ce0 = R_buf_im_2_ce0_local;

assign R_buf_im_3_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_3_ce0 = R_buf_im_3_ce0_local;

assign R_buf_im_4_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_4_ce0 = R_buf_im_4_ce0_local;

assign R_buf_im_5_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_5_ce0 = R_buf_im_5_ce0_local;

assign R_buf_im_6_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_6_ce0 = R_buf_im_6_ce0_local;

assign R_buf_im_7_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_7_ce0 = R_buf_im_7_ce0_local;

assign R_buf_im_8_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_8_ce0 = R_buf_im_8_ce0_local;

assign R_buf_im_9_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_9_ce0 = R_buf_im_9_ce0_local;

assign R_buf_im_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_im_ce0 = R_buf_im_ce0_local;

assign R_buf_re_10_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_10_ce0 = R_buf_re_10_ce0_local;

assign R_buf_re_11_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_11_ce0 = R_buf_re_11_ce0_local;

assign R_buf_re_12_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_12_ce0 = R_buf_re_12_ce0_local;

assign R_buf_re_13_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_13_ce0 = R_buf_re_13_ce0_local;

assign R_buf_re_14_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_14_ce0 = R_buf_re_14_ce0_local;

assign R_buf_re_15_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_15_ce0 = R_buf_re_15_ce0_local;

assign R_buf_re_16_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_16_ce0 = R_buf_re_16_ce0_local;

assign R_buf_re_17_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_17_ce0 = R_buf_re_17_ce0_local;

assign R_buf_re_18_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_18_ce0 = R_buf_re_18_ce0_local;

assign R_buf_re_19_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_19_ce0 = R_buf_re_19_ce0_local;

assign R_buf_re_1_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_1_ce0 = R_buf_re_1_ce0_local;

assign R_buf_re_20_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_20_ce0 = R_buf_re_20_ce0_local;

assign R_buf_re_2_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_2_ce0 = R_buf_re_2_ce0_local;

assign R_buf_re_3_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_3_ce0 = R_buf_re_3_ce0_local;

assign R_buf_re_4_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_4_ce0 = R_buf_re_4_ce0_local;

assign R_buf_re_5_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_5_ce0 = R_buf_re_5_ce0_local;

assign R_buf_re_6_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_6_ce0 = R_buf_re_6_ce0_local;

assign R_buf_re_7_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_7_ce0 = R_buf_re_7_ce0_local;

assign R_buf_re_8_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_8_ce0 = R_buf_re_8_ce0_local;

assign R_buf_re_9_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_9_ce0 = R_buf_re_9_ce0_local;

assign R_buf_re_address0 = zext_ln107_1_fu_922_p1;

assign R_buf_re_ce0 = R_buf_re_ce0_local;

assign add_ln105_1_fu_908_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign add_ln105_fu_876_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 9'd1);

assign add_ln107_fu_1136_p2 = (select_ln105_fu_900_p3 + 5'd1);

assign add_ln109_1_fu_1193_p2 = (add_ln109_fu_1188_p2 + zext_ln107_fu_1174_p1);

assign add_ln109_fu_1188_p2 = (zext_ln109_fu_1184_p1 + R);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_io_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (m_axi_gmem_0_AWREADY == 1'b0)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_io_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (m_axi_gmem_0_AWREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_io_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (m_axi_gmem_0_AWREADY == 1'b0)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state5_io_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (m_axi_gmem_0_AWREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b1));
end

assign ap_block_pp0_stage1_01001_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_WREADY == 1'b0));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_WREADY == 1'b0));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_0_WREADY == 1'b0));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io_grp1 = ((icmp_ln109_reg_1466 == 1'd0) & (m_axi_gmem_0_WREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln105_fu_882_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 9'd441) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_894_p2 = ((ap_sig_allocacmp_j_load == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_852_p2 = ((empty_25 == 3'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = sext_ln109_fu_1349_p1;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = select_ln109_cast_reg_1455;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_RREADY = 1'b0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign mul_ln109_fu_1168_p0 = mul_ln109_fu_1168_p00;

assign mul_ln109_fu_1168_p00 = select_ln105_1_reg_1479;

assign mul_ln109_fu_1168_p1 = 13'd168;

assign select_ln105_1_fu_914_p3 = ((icmp_ln107_fu_894_p2[0:0] == 1'b1) ? add_ln105_1_fu_908_p2 : ap_sig_allocacmp_i_load);

assign select_ln105_fu_900_p3 = ((icmp_ln107_fu_894_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign select_ln109_cast_fu_844_p1 = select_ln109;

assign sext_ln109_fu_1349_p1 = $signed(trunc_ln109_4_fu_1339_p4);

assign shl_ln109_3_fu_1177_p3 = {{select_ln105_reg_1474}, {3'd0}};

assign shl_ln109_fu_1377_p2 = zext_ln109_3_fu_1373_p1 << zext_ln109_1_cast_reg_1461;

assign tmp_2_fu_1269_p43 = 'bx;

assign tmp_3_fu_1367_p3 = {{tmp_2_reg_1916}, {tmp_reg_1911}};

assign tmp_fu_1199_p43 = 'bx;

assign trunc_ln109_4_fu_1339_p4 = {{add_ln109_1_fu_1193_p2[63:3]}};

assign trunc_ln109_fu_1382_p1 = shl_ln109_fu_1377_p2[63:0];

assign zext_ln107_1_fu_922_p1 = select_ln105_fu_900_p3;

assign zext_ln107_fu_1174_p1 = mul_ln109_reg_1696;

assign zext_ln109_1_cast_fu_848_p1 = zext_ln109_1;

assign zext_ln109_2_cast_fu_840_p1 = zext_ln109_2;

assign zext_ln109_3_fu_1373_p1 = tmp_3_fu_1367_p3;

assign zext_ln109_4_fu_1404_p1 = tmp_s_reg_1927;

assign zext_ln109_fu_1184_p1 = shl_ln109_3_fu_1177_p3;

always @ (posedge ap_clk) begin
    zext_ln109_2_cast_reg_1449[7] <= 1'b0;
    select_ln109_cast_reg_1455[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln109_1_cast_reg_1461[119:6] <= 114'b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
end

endmodule //covariance_estimation_covariance_estimation_Pipeline_WRITE_ROW_WRITE_COL
