# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/mvdrr_rdbs_kernel_0_0.xci
# IP: The module: 'mvdrr_rdbs_kernel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/hdl/ip/rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip/rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/constraints/rdbs_kernel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_rdbs_kernel_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.srcs/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/mvdrr_rdbs_kernel_0_0.xci
# IP: The module: 'mvdrr_rdbs_kernel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/hdl/ip/rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip/rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==rdbs_kernel_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Deepraj/Desktop/rdbs_mvdr/rdbs_mvdr.gen/sources_1/bd/mvdrr/ip/mvdrr_rdbs_kernel_0_0/constraints/rdbs_kernel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvdrr_rdbs_kernel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
